import "server-only";

import webpush from "web-push";
import { forgetSubscription } from "./store";

// Sending a notification to a device.
//
// ——— VAPID ———
//
// Three values, and none of them is an account with anybody: a key pair this
// app generates once, and a contact address that push services use to reach a
// human if a sender misbehaves. Apple, Google and Mozilla each run the actual
// delivery; VAPID is only how they know the messages are from us.
//
//   VAPID_PUBLIC_KEY    also sent to the browser — it is public by design
//   VAPID_PRIVATE_KEY   server only
//   VAPID_SUBJECT       mailto: or https:, whoever is responsible
//
// Generate a pair with `node scripts/vapid-keys.mjs`. They must stay stable:
// changing them orphans every subscription already granted, silently, because
// a subscription is bound to the key it was created with.
//
// ——— What this never becomes ———
//
// An order's own progress, and nothing else. Push permission is granted for
// "tell me about my bagels", and a marketing message through that channel is
// the fastest way to have it revoked and the app uninstalled. The drop list is
// where anything promotional belongs, and it is a mailing list somebody opted
// into separately.

export type PushPayload = {
  title: string;
  body: string;
  /** Where tapping it goes. Same-origin path. */
  url: string;
  /** Collapses replacements: a second notification with the same tag replaces
   *  the first rather than stacking. Order progress is one story, so a phone
   *  should show its latest chapter and not four of them. */
  tag: string;
};

// ——— These cannot be generated by a hosting dashboard ———
//
// A VAPID pair is an ECDSA P-256 key pair: the public half is a 65-byte
// uncompressed point and the private half is the 32-byte scalar it was derived
// from, and they are mathematically related. A platform's "generate a random
// value for me" button produces neither — it produces a random string, and two
// random strings are not a pair.
//
// That failure is quiet in the worst way. setVapidDetails may accept
// something of roughly the right shape, browsers will happily create
// subscriptions against the public key, and every send afterwards is rejected
// by the push service — so customers grant permission, see the toggle turn on,
// and never receive anything.
//
// So the shape is checked, in base64url and by decoded length, and a value
// that cannot be a key says so by name.
const PUBLIC_BYTES = 65;
const PRIVATE_BYTES = 32;

function decodedLength(value: string): number | null {
  if (!/^[A-Za-z0-9_-]+$/.test(value)) return null;
  try {
    return Buffer.from(value, "base64url").length;
  } catch {
    return null;
  }
}

function keyProblem(): string | null {
  const publicHalf = process.env.VAPID_PUBLIC_KEY;
  const privateHalf = process.env.VAPID_PRIVATE_KEY;
  const subject = process.env.VAPID_SUBJECT;

  const missing = [
    ["VAPID_PUBLIC_KEY", publicHalf],
    ["VAPID_PRIVATE_KEY", privateHalf],
    ["VAPID_SUBJECT", subject],
  ]
    .filter(([, value]) => !value)
    .map(([name]) => name);
  if (missing.length > 0) return `${missing.join(", ")} not set`;

  if (decodedLength(publicHalf as string) !== PUBLIC_BYTES) {
    return (
      "VAPID_PUBLIC_KEY is not a P-256 public key — it must be" +
      ` ${PUBLIC_BYTES} bytes of base64url. A randomly generated value cannot be one;` +
      " run `node scripts/vapid-keys.mjs` and paste both halves of the pair"
    );
  }
  if (decodedLength(privateHalf as string) !== PRIVATE_BYTES) {
    return (
      "VAPID_PRIVATE_KEY is not a P-256 private key — it must be" +
      ` ${PRIVATE_BYTES} bytes of base64url, and it must be the half generated` +
      " alongside the public key above, not a separate random value"
    );
  }
  if (!/^(mailto:|https:)/.test(subject as string)) {
    return "VAPID_SUBJECT must start with mailto: or https:";
  }
  return null;
}

export function isPushConfigured(): boolean {
  return keyProblem() === null;
}

/** The reason push is off, for a log or a diagnostic. Null when it is on. */
export function pushProblem(): string | null {
  return keyProblem();
}

export function publicKey(): string | null {
  return process.env.VAPID_PUBLIC_KEY ?? null;
}

let armed = false;

function arm(): boolean {
  if (armed) return true;
  if (!isPushConfigured()) return false;
  webpush.setVapidDetails(
    process.env.VAPID_SUBJECT as string,
    process.env.VAPID_PUBLIC_KEY as string,
    process.env.VAPID_PRIVATE_KEY as string,
  );
  armed = true;
  return true;
}

/** Send one payload to a set of devices.
 *
 *  Takes the devices rather than an order id, because the message differs by
 *  language and the caller has already grouped them — see announce.ts.
 *
 *  Never throws. A notification is the least important thing happening at the
 *  moment it is sent: the webhook that triggered it has an order to record and
 *  a customer refreshing a tracker, so a push service having a bad minute must
 *  not become a failed webhook that the provider then retries. */
export async function notifyDevices(
  devices: { endpoint: string; p256dh: string; auth: string }[],
  payload: PushPayload,
): Promise<number> {
  if (!arm()) {
    console.warn(`[push] not sending: ${pushProblem()}`);
    return 0;
  }
  if (devices.length === 0) return 0;

  const body = JSON.stringify(payload);
  let delivered = 0;

  await Promise.all(
    devices.map(async (device) => {
      try {
        await webpush.sendNotification(
          { endpoint: device.endpoint, keys: { p256dh: device.p256dh, auth: device.auth } },
          body,
          // Long enough to survive a phone in a lift, short enough that a
          // "your order is ready" never arrives the following morning.
          { TTL: 1800 },
        );
        delivered += 1;
      } catch (error) {
        const status = (error as { statusCode?: number }).statusCode;
        // 404 and 410 are the push service saying this subscription is gone —
        // uninstalled, permission revoked, expired. Keeping it would mean
        // retrying a dead endpoint on every future update.
        if (status === 404 || status === 410) {
          await forgetSubscription(device.endpoint);
        } else {
          console.error(`[push] send failed (${status ?? "no status"}) for one device`);
        }
      }
    }),
  );
  return delivered;
}
