import { EN_POLICIES, type Policy, type PolicyBlock, type PolicyPacks } from "./policy";

// The two legal pages in the other six languages.
//
// Stored as a flat run of strings rather than as a second copy of the document
// tree, and rebuilt against the English structure below. The structure — which
// section has a bulleted list, which line is bold — is the same document in
// every language and is not a translator's decision; only the words change. A
// tree per language would have been six chances to drop a bullet.
//
// The order is exactly the order the strings appear on the page: the title,
// the dated lines under it, then every heading, paragraph, label and bullet in
// turn. `check()` below fails the build if a run is the wrong length, which is
// the failure this shape can actually have.

function rebuild(source: Policy, words: string[]): Policy {
  let at = 0;
  const next = () => {
    const word = words[at++];
    if (word === undefined) {
      throw new Error(`policyPacks: ran out of strings at ${at - 1}`);
    }
    return word;
  };

  const block = (b: PolicyBlock): PolicyBlock => {
    if (b.kind === "p" || b.kind === "strong") return { ...b, text: next() };
    if (b.kind === "kv") {
      return {
        kind: "kv",
        items: b.items.map(() => ({ label: next(), text: next() })),
      };
    }
    return {
      kind: "list",
      ...(b.heading ? { heading: next() } : {}),
      ...(b.lead ? { lead: next() } : {}),
      items: b.items.map(() => next()),
    };
  };

  const title = next();
  const meta = source.meta.map(() => next());
  const intro = source.intro.map(block);
  const sections = source.sections.map((section) => ({
    heading: next(),
    blocks: section.blocks.map(block),
  }));

  if (at !== words.length) {
    throw new Error(`policyPacks: ${words.length - at} strings left over`);
  }
  return { title, meta, intro, sections };
}

// ——— Spanish ———

const esCookie = [
  "Política de Cookies",
  "Operado por Public Entity Holdings",
  "Última actualización: 1 de agosto de 2026",
  "1. Introducción",
  "Esta Política de Cookies explica cómo Corner Bagel (“Corner Bagel”, “nosotros”, “nuestro” o “nos”), operado por Public Entity Holdings, utiliza cookies y tecnologías de seguimiento similares en nuestro sitio web. Esta política debe leerse junto con nuestra {privacyPolicy}.",
  "Esta política está dirigida a los visitantes que usan nuestro sitio web en los Estados Unidos, incluida California. Cuando la ley aplicable lo exija, incluida la Ley de Privacidad del Consumidor de California (CCPA) en su versión modificada por la Ley de Derechos de Privacidad de California (CPRA), obtendremos su consentimiento antes de instalar cookies no esenciales.",
  "2. ¿Qué son las cookies?",
  "Las cookies son pequeños archivos de texto que se guardan en su dispositivo cuando visita nuestro sitio web. Sirven para reconocer su dispositivo, recordar preferencias, mejorar el funcionamiento del sitio y permitir los pedidos en línea. Las cookies pueden ser de sesión o persistentes, y pueden ser propias o de terceros.",
  "3. Cómo usamos las cookies",
  "Usamos cookies para que nuestro sitio web funcione de forma correcta y segura; para recordar sus preferencias; para personalizar su experiencia; para analizar el rendimiento del sitio (si se activa en el futuro); y para dar servicio a los pedidos en línea, incluidos los gestionados por Toast. No usamos cookies para recopilar información personal sensible más allá de lo necesario para prestar los servicios que usted solicita.",
  "4. Categorías de cookies que utilizamos",
  "Estrictamente necesarias",
  "Imprescindibles para la seguridad, la gestión de la sesión, la prevención del fraude, el pago y el funcionamiento del sitio web. No requieren consentimiento.",
  "Funcionales",
  "Recuerdan los ajustes de accesibilidad y las preferencias de pedido. Requieren consentimiento cuando corresponde.",
  "Analíticas",
  "No están activas actualmente. Si se introducen, nos ayudarán a entender el uso del sitio web y solo se activarán tras obtener su consentimiento.",
  "Publicidad/Marketing",
  "Corner Bagel no utiliza actualmente cookies de publicidad ni de marketing.",
  "5. Cookies estrictamente necesarias",
  "Estas cookies son necesarias para navegar por el sitio web, consultar los menús, enviar formularios de contacto y completar pedidos en línea. Sin ellas no es posible prestar los servicios solicitados.",
  "6. Cookies funcionales",
  "Las cookies funcionales recuerdan sus preferencias y mejoran su experiencia. Estas cookies no siguen su actividad en otros sitios web y solo se usan cuando la ley lo permite.",
  "7. Cookies analíticas",
  "Corner Bagel no utiliza actualmente cookies analíticas. Si en el futuro se añaden herramientas de análisis, se avisará a los visitantes y se les dará la oportunidad de dar su consentimiento antes de activarlas.",
  "8. Cookies de publicidad y marketing",
  "Corner Bagel no instala actualmente cookies de publicidad ni de retargeting. No vendemos la información personal recopilada mediante cookies con fines publicitarios.",
  "9. Cookies de terceros",
  "Nuestro sitio web puede usar servicios de terceros, incluido Toast para los pedidos en línea. Estos proveedores pueden instalar sus propias cookies, sujetas a sus propias políticas de privacidad y de cookies.",
  "10. Pedidos con Toast",
  "Cuando utiliza la plataforma de pedidos en línea gestionada por Toast, Toast puede instalar las cookies necesarias para que el pedido funcione. Las prácticas de privacidad y de cookies de Toast se rigen por las políticas del propio Toast. Corner Bagel recomienda a sus clientes revisarlas antes de hacer un pedido.",
  "11. Gestión de las preferencias de cookies",
  "Puede aceptar, rechazar o personalizar las cookies no esenciales desde nuestro aviso de cookies. Las preferencias pueden cambiarse en cualquier momento.",
  "12. Controles del navegador",
  "La mayoría de los navegadores permiten bloquear o eliminar cookies. Bloquear las cookies estrictamente necesarias puede impedir que partes del sitio web, incluidos los pedidos en línea, funcionen correctamente.",
  "13. Consentimiento y retirada",
  "Cuando la ley lo exige, obtenemos su consentimiento antes de instalar cookies no esenciales. El consentimiento puede retirarse en cualquier momento desde el centro de preferencias de cookies o desde los ajustes del navegador.",
  "14. Compartir datos",
  "Podemos compartir información relacionada con las cookies con proveedores de confianza que nos ayudan a operar el sitio web o a procesar pedidos en línea, incluido Toast, o cuando la ley lo exija. No vendemos la información personal recopilada mediante cookies.",
  "15. Cambios",
  "Podemos actualizar esta Política de Cookies de vez en cuando. Los cambios importantes se reflejarán actualizando la fecha de última actualización.",
  "16. Información de contacto",
  "Corner Bagel, operado por Public Entity Holdings. Correo: {email}",
  "Si tiene preguntas sobre esta Política de Cookies o sobre sus derechos de privacidad, escríbanos al correo indicado arriba.",
];

const esPrivacy = [
  "Política de Privacidad",
  "Fecha de entrada en vigor: 8 de julio de 2026",
  "En Corner Bagel (“Corner Bagel”, “nosotros”, “nuestro” o “nos”) respetamos su privacidad. Esta política explica cómo recopilamos, usamos, divulgamos y protegemos la información cuando visita nuestro sitio web, hace un pedido, se apunta a nuestra lista de correo, participa en promociones o se relaciona de cualquier otro modo con nuestro negocio.",
  "Al usar nuestro sitio web o nuestros servicios, usted acepta esta Política de Privacidad.",
  "Información que recopilamos",
  "Información que usted nos facilita",
  "Podemos recopilar:",
  "Nombre",
  "Dirección de correo electrónico",
  "Número de teléfono",
  "Información de facturación y pago",
  "Información de entrega o recogida",
  "Historial de pedidos",
  "Información de la cuenta de fidelidad o recompensas (si procede)",
  "Información recopilada automáticamente",
  "Cuando visita nuestro sitio web, podemos recopilar:",
  "Dirección IP",
  "Tipo de navegador",
  "Información del dispositivo",
  "Sistema operativo",
  "Páginas visitadas",
  "Tiempo pasado en nuestro sitio web",
  "Sitios web de procedencia",
  "Cookies y tecnologías similares",
  "Cómo usamos su información",
  "Usamos su información para:",
  "Procesar y preparar pedidos",
  "Comunicarnos con usted sobre sus pedidos",
  "Prestar atención al cliente",
  "Mejorar nuestros productos y servicios",
  "Personalizar su experiencia",
  "Enviar boletines, promociones y ofertas especiales (cuando usted se suscribe)",
  "Gestionar programas de fidelidad o recompensas",
  "Prevenir el fraude y mantener la seguridad",
  "Cumplir obligaciones legales",
  "Comunicaciones de marketing",
  "Si se suscribe a nuestra lista de correo, podemos enviarle novedades sobre:",
  "Nuevos artículos del menú",
  "Propuestas de temporada",
  "Promociones",
  "Eventos",
  "Avisos de la tienda",
  "Puede darse de baja en cualquier momento con el enlace de baja que incluimos en nuestros correos.",
  "Cookies y seguimiento",
  "Nuestro sitio web puede usar cookies y tecnologías similares para:",
  "Recordar las preferencias del usuario",
  "Mejorar el funcionamiento del sitio web",
  "Analizar el tráfico del sitio web",
  "Medir la eficacia del marketing",
  "La mayoría de los navegadores permiten desactivar las cookies desde sus ajustes, aunque hacerlo puede afectar a ciertas funciones del sitio web.",
  "Información de pago",
  "Los pagos se procesan a través de proveedores de pago externos de confianza.",
  "Corner Bagel no guarda números completos de tarjeta de pago en nuestros servidores.",
  "Cómo compartimos la información",
  "No vendemos su información personal.",
  "Podemos compartir información con proveedores de confianza que nos ayudan a operar nuestro negocio, entre ellos:",
  "Procesadores de pago",
  "Proveedores de pedidos en línea",
  "Socios de reparto",
  "Plataformas de email marketing",
  "Proveedores de alojamiento web",
  "Proveedores de analítica",
  "Estos proveedores solo pueden usar su información para prestar servicios en nuestro nombre. También podemos divulgar información si la ley lo exige o para proteger nuestros derechos legales.",
  "Seguridad de los datos",
  "Aplicamos medidas administrativas, técnicas y físicas comercialmente razonables para proteger su información.",
  "Aunque nos esforzamos por proteger su información, ningún método de transmisión o almacenamiento electrónico es completamente seguro.",
  "Conservación de los datos",
  "Conservamos la información personal solo el tiempo necesario para:",
  "Preparar pedidos",
  "Prestar los servicios solicitados",
  "Cumplir requisitos legales y contables",
  "Resolver disputas",
  "Hacer valer nuestros acuerdos",
  "Sus derechos de privacidad",
  "Según su estado o país de residencia, puede tener derechos sobre su información personal, entre ellos:",
  "Acceder a su información",
  "Corregir información inexacta",
  "Solicitar la eliminación de información personal",
  "Solicitar una copia de su información",
  "Darse de baja de determinadas comunicaciones de marketing",
  "Para ejercer estos derechos, escríbanos a {email}.",
  "Personas que solicitan empleo",
  "Si solicita un puesto de trabajo con nosotros, recopilamos lo que introduce en el formulario de solicitud: su nombre y datos de contacto, la ciudad en la que vive, los puestos y la disponibilidad que marca, los estudios, la experiencia laboral y las referencias que decida añadir, y sus respuestas escritas. Lo usamos para decidir si le llamamos a una entrevista, y para nada más.",
  "No preguntamos a quienes solicitan empleo por su raza, religión, edad, discapacidad, nacionalidad, género, orientación sexual, estado civil ni condición de veterano, y no lo tenemos en cuenta. No realizamos comprobaciones de antecedentes a través de este formulario. Si en algún momento pasaran a formar parte del proceso de contratación, pediríamos su autorización por separado y por escrito, tal como exige la ley federal.",
  "Las solicitudes se envían como documento a nuestro correo de contratación. No se añaden a ninguna base de datos de clientes ni se usan para marketing. Las conservamos hasta un año y después las eliminamos. Quienes solicitan empleo tienen los mismos derechos descritos arriba —acceso, corrección, eliminación y copia— y pueden ejercerlos escribiendo a {email}.",
  "Mientras rellenas el formulario, se guarda un borrador sin terminar en tu propio navegador para que puedas retomarlo. No nos llega, se borra cuando lo envías o si lo dejas quince minutos, y «Empezar de nuevo» lo elimina al instante. Si escribes tus respuestas en un idioma distinto del inglés, las traducimos para poder leerlas y conservamos junto a la traducción lo que escribiste realmente.",
  "Privacidad de los menores",
  "Nuestros servicios no están dirigidos a menores de 13 años y no recopilamos conscientemente información personal de menores. Si detectamos que se ha recopilado información de un menor sin el consentimiento adecuado, la eliminaremos de inmediato.",
  "Enlaces a terceros",
  "Nuestro sitio web puede contener enlaces a sitios web o servicios de terceros. No somos responsables de las prácticas de privacidad ni del contenido de esos terceros.",
  "Actualizaciones",
  "Podemos actualizar esta Política de Privacidad de vez en cuando. Cuando haya cambios, revisaremos la fecha de entrada en vigor que aparece arriba. El uso continuado de nuestros servicios tras una actualización supone la aceptación de la política revisada.",
  "Contacto",
  "Corner Bagel. Correo: {email}",
];

// ——— Korean ———

const koCookie = [
  "쿠키 정책",
  "운영: Public Entity Holdings",
  "최종 업데이트: 2026년 8월 1일",
  "1. 개요",
  "이 쿠키 정책은 Public Entity Holdings가 운영하는 Corner Bagel(이하 “Corner Bagel”, “당사”)이 웹사이트에서 쿠키 및 유사한 추적 기술을 어떻게 사용하는지 설명합니다. 이 정책은 당사의 {privacyPolicy}와 함께 읽어 주시기 바랍니다.",
  "이 정책은 캘리포니아주를 포함한 미국에서 당사 웹사이트를 이용하는 방문자를 대상으로 합니다. 캘리포니아 프라이버시 권리법(CPRA)으로 개정된 캘리포니아 소비자 프라이버시법(CCPA)을 비롯한 관련 법률이 요구하는 경우, 필수가 아닌 쿠키를 설정하기 전에 동의를 받습니다.",
  "2. 쿠키란 무엇입니까?",
  "쿠키는 웹사이트를 방문할 때 기기에 저장되는 작은 텍스트 파일입니다. 기기를 인식하고, 설정을 기억하고, 기능을 개선하고, 온라인 주문을 지원하는 데 쓰입니다. 쿠키는 세션 쿠키일 수도 지속 쿠키일 수도 있으며, 자사 쿠키일 수도 제3자 쿠키일 수도 있습니다.",
  "3. 쿠키 사용 방법",
  "당사는 웹사이트가 정확하고 안전하게 작동하도록 하기 위해, 설정을 기억하기 위해, 이용 경험을 개인화하기 위해, (향후 도입될 경우) 웹사이트 성능을 분석하기 위해, 그리고 Toast가 제공하는 서비스를 포함한 온라인 주문을 지원하기 위해 쿠키를 사용합니다. 요청하신 서비스를 제공하는 데 필요한 범위를 넘어 민감한 개인정보를 수집하는 데에는 쿠키를 사용하지 않습니다.",
  "4. 당사가 사용하는 쿠키의 종류",
  "필수 쿠키",
  "보안, 세션 관리, 사기 방지, 결제, 웹사이트 기능에 반드시 필요합니다. 동의가 필요하지 않습니다.",
  "기능 쿠키",
  "접근성 설정과 주문 관련 설정을 기억합니다. 해당하는 경우 동의가 필요합니다.",
  "분석 쿠키",
  "현재 사용하지 않습니다. 도입될 경우 웹사이트 이용 현황을 파악하는 데 쓰이며, 동의를 받은 뒤에만 활성화됩니다.",
  "광고/마케팅 쿠키",
  "Corner Bagel은 현재 광고나 마케팅 쿠키를 사용하지 않습니다.",
  "5. 필수 쿠키",
  "이 쿠키는 웹사이트 탐색, 메뉴 확인, 문의 양식 제출, 온라인 주문 완료에 반드시 필요합니다. 이 쿠키가 없으면 요청하신 서비스를 제공할 수 없습니다.",
  "6. 기능 쿠키",
  "기능 쿠키는 설정을 기억해 이용 경험을 개선합니다. 이 쿠키는 다른 웹사이트에서의 활동을 추적하지 않으며, 법이 허용하는 범위에서만 사용됩니다.",
  "7. 분석 쿠키",
  "Corner Bagel은 현재 분석 쿠키를 사용하지 않습니다. 향후 분석 도구를 도입하는 경우 방문자에게 안내하고, 활성화 전에 동의할 기회를 드립니다.",
  "8. 광고 및 마케팅 쿠키",
  "Corner Bagel은 현재 광고나 리타게팅 쿠키를 설정하지 않습니다. 쿠키로 수집한 개인정보를 광고 목적으로 판매하지 않습니다.",
  "9. 제3자 쿠키",
  "당사 웹사이트는 온라인 주문을 위한 Toast를 포함해 제3자 서비스를 사용할 수 있습니다. 이러한 제공업체는 각자의 개인정보 및 쿠키 정책에 따라 자체 쿠키를 설정할 수 있습니다.",
  "10. Toast 주문",
  "Toast가 제공하는 온라인 주문 플랫폼을 이용하실 때, Toast는 주문 기능에 필요한 쿠키를 설정할 수 있습니다. Toast의 개인정보 및 쿠키 처리 방침은 Toast 자체 정책의 적용을 받습니다. Corner Bagel은 주문 전에 해당 정책을 확인하시기를 권장합니다.",
  "11. 쿠키 설정 관리",
  "쿠키 배너에서 필수가 아닌 쿠키를 수락하거나 거부하거나 개별 설정할 수 있습니다. 설정은 언제든지 변경할 수 있습니다.",
  "12. 브라우저 설정",
  "대부분의 브라우저에서 쿠키를 차단하거나 삭제할 수 있습니다. 필수 쿠키를 차단하면 온라인 주문을 포함한 웹사이트의 일부가 정상적으로 작동하지 않을 수 있습니다.",
  "13. 동의와 철회",
  "법이 요구하는 경우, 필수가 아닌 쿠키를 설정하기 전에 동의를 받습니다. 동의는 쿠키 설정 센터나 브라우저 설정을 통해 언제든지 철회할 수 있습니다.",
  "14. 정보 공유",
  "당사는 웹사이트 운영이나 온라인 주문 처리를 돕는 신뢰할 수 있는 서비스 제공업체(Toast 포함)와, 또는 법이 요구하는 경우에 쿠키 관련 정보를 공유할 수 있습니다. 쿠키로 수집한 개인정보를 판매하지 않습니다.",
  "15. 변경",
  "당사는 이 쿠키 정책을 수시로 업데이트할 수 있습니다. 중요한 변경 사항은 최종 업데이트 날짜를 갱신하는 방식으로 반영합니다.",
  "16. 연락처",
  "Corner Bagel, 운영: Public Entity Holdings. 이메일: {email}",
  "이 쿠키 정책이나 개인정보 권리에 관해 궁금한 점이 있으시면 위 이메일로 연락해 주세요.",
];

const koPrivacy = [
  "개인정보 처리방침",
  "시행일: 2026년 7월 8일",
  "Corner Bagel(이하 “Corner Bagel”, “당사”)은 여러분의 개인정보를 존중합니다. 이 방침은 여러분이 당사 웹사이트를 방문하거나, 주문을 하거나, 메일링 리스트에 가입하거나, 프로모션에 참여하거나, 그 밖의 방식으로 당사와 관계를 맺을 때 당사가 정보를 어떻게 수집·이용·제공·보호하는지 설명합니다.",
  "당사 웹사이트나 서비스를 이용하시면 이 개인정보 처리방침에 동의하시는 것으로 봅니다.",
  "수집하는 정보",
  "직접 제공하시는 정보",
  "다음을 수집할 수 있습니다:",
  "이름",
  "이메일 주소",
  "전화번호",
  "청구 및 결제 정보",
  "배달 또는 픽업 정보",
  "주문 내역",
  "적립 또는 리워드 계정 정보(해당하는 경우)",
  "자동으로 수집되는 정보",
  "웹사이트를 방문하실 때 다음을 수집할 수 있습니다:",
  "IP 주소",
  "브라우저 종류",
  "기기 정보",
  "운영체제",
  "방문한 페이지",
  "웹사이트 체류 시간",
  "유입 경로 웹사이트",
  "쿠키 및 유사 기술",
  "정보의 이용 방법",
  "당사는 다음을 위해 정보를 이용합니다:",
  "주문 처리 및 이행",
  "주문 관련 연락",
  "고객 지원 제공",
  "제품과 서비스 개선",
  "이용 경험 개인화",
  "뉴스레터, 프로모션, 특별 혜택 발송(수신 동의 시)",
  "적립 또는 리워드 프로그램 운영",
  "사기 방지 및 보안 유지",
  "법적 의무 준수",
  "마케팅 커뮤니케이션",
  "메일링 리스트에 가입하시면 다음에 관한 소식을 보내드릴 수 있습니다:",
  "새로운 메뉴",
  "시즌 한정 메뉴",
  "프로모션",
  "이벤트",
  "매장 공지",
  "이메일에 포함된 수신 거부 링크로 언제든지 구독을 해지하실 수 있습니다.",
  "쿠키와 추적",
  "당사 웹사이트는 다음을 위해 쿠키 및 유사 기술을 사용할 수 있습니다:",
  "이용자 설정 기억",
  "웹사이트 기능 개선",
  "웹사이트 트래픽 분석",
  "마케팅 효과 측정",
  "대부분의 브라우저에서 설정을 통해 쿠키를 비활성화할 수 있지만, 그렇게 하면 웹사이트의 일부 기능에 영향을 줄 수 있습니다.",
  "결제 정보",
  "결제는 신뢰할 수 있는 외부 결제 제공업체를 통해 처리됩니다.",
  "Corner Bagel은 결제 카드 전체 번호를 서버에 저장하지 않습니다.",
  "정보의 제공",
  "당사는 여러분의 개인정보를 판매하지 않습니다.",
  "당사는 사업 운영을 돕는 신뢰할 수 있는 서비스 제공업체와 정보를 공유할 수 있으며, 여기에는 다음이 포함됩니다:",
  "결제 처리업체",
  "온라인 주문 제공업체",
  "배달 파트너",
  "이메일 마케팅 플랫폼",
  "웹사이트 호스팅 제공업체",
  "분석 제공업체",
  "이러한 제공업체는 당사를 대신해 서비스를 수행하기 위한 목적으로만 정보를 이용할 수 있습니다. 법이 요구하는 경우나 당사의 법적 권리를 보호하기 위해 정보를 제공할 수도 있습니다.",
  "정보 보안",
  "당사는 여러분의 정보를 보호하기 위해 상업적으로 합리적인 관리적·기술적·물리적 보호 조치를 시행합니다.",
  "정보를 보호하기 위해 노력하고 있으나, 전자적 전송이나 저장 방식 가운데 완벽하게 안전한 것은 없습니다.",
  "정보 보관",
  "당사는 다음에 필요한 기간에 한해 개인정보를 보관합니다:",
  "주문 이행",
  "요청하신 서비스 제공",
  "법률 및 회계 요건 충족",
  "분쟁 해결",
  "계약의 이행",
  "여러분의 개인정보 권리",
  "거주하시는 주 또는 국가에 따라 개인정보에 관한 다음과 같은 권리를 가지실 수 있습니다:",
  "정보 열람",
  "부정확한 정보의 정정",
  "개인정보 삭제 요청",
  "정보 사본 요청",
  "일부 마케팅 수신 거부",
  "이러한 권리를 행사하시려면 {email}로 연락해 주세요.",
  "채용 지원자",
  "채용에 지원하시면 지원서에 입력하신 내용을 수집합니다. 성명과 연락처, 거주 도시, 선택하신 직무와 근무 가능 시간, 직접 추가하신 학력·경력·추천인, 그리고 작성하신 답변입니다. 면접 여부를 정하는 데에만 사용하며 다른 용도로는 쓰지 않습니다.",
  "지원자에게 인종, 종교, 나이, 장애, 출신 국가, 성별, 성적 지향, 혼인 여부, 병역 사항은 묻지 않으며 고려하지도 않습니다. 이 지원서로는 신원 조회를 하지 않습니다. 신원 조회가 채용 절차에 포함되는 경우에는 연방법에 따라 별도의 서면 동의를 요청드립니다.",
  "지원서는 문서 형태로 채용 담당 이메일로 전달됩니다. 고객 데이터베이스에 추가되지 않으며 마케팅에 사용되지 않습니다. 최대 1년간 보관한 뒤 삭제합니다. 지원자도 위에 설명한 권리(열람, 정정, 삭제, 사본 요청)를 동일하게 가지며 {email}로 연락해 행사하실 수 있습니다.",
  "작성하시는 동안 미완성 임시 저장본이 이용자 브라우저에 보관되어 이어서 작성하실 수 있습니다. 저희에게 전송되지 않으며 제출 시 또는 15분간 그대로 두면 삭제되고, “새로 시작”을 누르면 즉시 지워집니다. 영어 외의 언어로 작성하시면 저희가 읽을 수 있도록 번역하며, 원문도 번역문과 함께 보관합니다.",
  "아동의 개인정보",
  "당사 서비스는 만 13세 미만 아동을 대상으로 하지 않으며, 아동의 개인정보를 알면서 수집하지 않습니다. 적절한 동의 없이 아동의 정보가 수집된 사실을 알게 되면 즉시 삭제합니다.",
  "외부 링크",
  "당사 웹사이트에는 제3자 웹사이트나 서비스로 연결되는 링크가 있을 수 있습니다. 당사는 해당 제3자의 개인정보 처리 방식이나 콘텐츠에 대해 책임지지 않습니다.",
  "변경",
  "당사는 이 개인정보 처리방침을 수시로 업데이트할 수 있습니다. 변경이 있을 경우 위의 시행일을 갱신합니다. 업데이트 이후에도 서비스를 계속 이용하시면 변경된 방침에 동의하신 것으로 봅니다.",
  "연락처",
  "Corner Bagel. 이메일: {email}",
];

// ——— Urdu ———

const urCookie = [
  "کوکی پالیسی",
  "Public Entity Holdings کے زیرِ انتظام",
  "آخری بار اپ ڈیٹ: 1 اگست 2026",
  "1. تعارف",
  "یہ کوکی پالیسی بتاتی ہے کہ Public Entity Holdings کے زیرِ انتظام چلنے والا Corner Bagel (“Corner Bagel”، “ہم”، “ہمارا”) اپنی ویب سائٹ پر کوکیز اور اس جیسی ٹریکنگ ٹیکنالوجیز کیسے استعمال کرتا ہے۔ اسے ہماری {privacyPolicy} کے ساتھ ملا کر پڑھا جائے۔",
  "یہ پالیسی ان لوگوں کے لیے ہے جو امریکہ میں، بشمول کیلیفورنیا، ہماری ویب سائٹ استعمال کرتے ہیں۔ جہاں قابلِ اطلاق قانون تقاضا کرے، بشمول کیلیفورنیا کنزیومر پرائیویسی ایکٹ (CCPA) جیسا کہ کیلیفورنیا پرائیویسی رائٹس ایکٹ (CPRA) سے ترمیم شدہ ہے، ہم غیر ضروری کوکیز رکھنے سے پہلے رضامندی حاصل کریں گے۔",
  "2. کوکیز کیا ہیں؟",
  "کوکیز چھوٹی ٹیکسٹ فائلیں ہیں جو ہماری ویب سائٹ پر آنے پر آپ کے آلے میں محفوظ ہو جاتی ہیں۔ یہ آپ کے آلے کو پہچاننے، ترجیحات یاد رکھنے، کارکردگی بہتر بنانے اور آن لائن آرڈرنگ چلانے میں مدد دیتی ہیں۔ کوکیز سیشن کوکیز یا مستقل کوکیز ہو سکتی ہیں، اور اپنی یا کسی تیسرے فریق کی ہو سکتی ہیں۔",
  "3. ہم کوکیز کیسے استعمال کرتے ہیں",
  "ہم کوکیز اس لیے استعمال کرتے ہیں کہ ہماری ویب سائٹ درست اور محفوظ طریقے سے چلے؛ آپ کی ترجیحات یاد رہیں؛ آپ کا تجربہ ذاتی نوعیت کا ہو؛ ویب سائٹ کی کارکردگی کا تجزیہ ہو سکے (اگر مستقبل میں فعال کیا گیا)؛ اور آن لائن آرڈرنگ کی خدمات چل سکیں، بشمول وہ جو Toast کے ذریعے چلتی ہیں۔ ہم کوکیز کے ذریعے حساس ذاتی معلومات اس سے زیادہ جمع نہیں کرتے جتنی آپ کی درخواست کردہ خدمات مکمل کرنے کے لیے ضروری ہوں۔",
  "4. ہم جن اقسام کی کوکیز استعمال کرتے ہیں",
  "لازمی",
  "سیکیورٹی، سیشن کے انتظام، دھوکہ دہی کی روک تھام، چیک آؤٹ اور ویب سائٹ کے کام کرنے کے لیے ضروری۔ رضامندی درکار نہیں۔",
  "فنکشنل",
  "رسائی کی ترتیبات اور آرڈر کی ترجیحات یاد رکھتی ہیں۔ جہاں لاگو ہو وہاں رضامندی درکار ہے۔",
  "تجزیاتی",
  "فی الحال فعال نہیں۔ اگر متعارف کرائی گئیں تو یہ ویب سائٹ کے استعمال کو سمجھنے میں مدد دیں گی اور صرف رضامندی کے بعد فعال ہوں گی۔",
  "اشتہاری/مارکیٹنگ",
  "Corner Bagel فی الحال اشتہاری یا مارکیٹنگ کوکیز استعمال نہیں کرتا۔",
  "5. لازمی کوکیز",
  "یہ کوکیز ویب سائٹ دیکھنے، مینو دیکھنے، رابطہ فارم بھیجنے اور آن لائن آرڈر مکمل کرنے کے لیے ضروری ہیں۔ ان کے بغیر مطلوبہ خدمات فراہم نہیں کی جا سکتیں۔",
  "6. فنکشنل کوکیز",
  "فنکشنل کوکیز آپ کی ترجیحات یاد رکھتی ہیں اور آپ کا تجربہ بہتر بناتی ہیں۔ یہ کوکیز دوسری ویب سائٹس پر آپ کی سرگرمی کا پیچھا نہیں کرتیں اور صرف وہیں استعمال ہوتی ہیں جہاں قانون اجازت دے۔",
  "7. تجزیاتی کوکیز",
  "Corner Bagel فی الحال تجزیاتی کوکیز استعمال نہیں کرتا۔ اگر مستقبل میں تجزیاتی ٹولز شامل کیے گئے تو آنے والوں کو مطلع کیا جائے گا اور فعال کرنے سے پہلے رضامندی کا موقع دیا جائے گا۔",
  "8. اشتہاری اور مارکیٹنگ کوکیز",
  "Corner Bagel فی الحال اشتہاری یا ری ٹارگٹنگ کوکیز نہیں رکھتا۔ ہم کوکیز کے ذریعے جمع کی گئی ذاتی معلومات اشتہاری مقاصد کے لیے فروخت نہیں کرتے۔",
  "9. تیسرے فریق کی کوکیز",
  "ہماری ویب سائٹ تیسرے فریق کی خدمات استعمال کر سکتی ہے، بشمول آن لائن آرڈرنگ کے لیے Toast۔ یہ فراہم کنندگان اپنی رازداری اور کوکی پالیسیوں کے تحت اپنی کوکیز رکھ سکتے ہیں۔",
  "10. Toast سے آرڈر",
  "جب آپ Toast کا چلایا ہوا آن لائن آرڈرنگ پلیٹ فارم استعمال کرتے ہیں تو Toast آرڈرنگ چلانے کے لیے ضروری کوکیز رکھ سکتا ہے۔ Toast کی رازداری اور کوکی سے متعلق روش خود Toast کی پالیسیوں کے تابع ہے۔ Corner Bagel گاہکوں کو مشورہ دیتا ہے کہ آرڈر دینے سے پہلے وہ پالیسیاں دیکھ لیں۔",
  "11. کوکی ترجیحات کا انتظام",
  "آپ ہمارے کوکی بینر سے غیر ضروری کوکیز قبول، مسترد یا اپنی مرضی کے مطابق مقرر کر سکتے ہیں۔ ترجیحات کسی بھی وقت بدلی جا سکتی ہیں۔",
  "12. براؤزر کے کنٹرول",
  "زیادہ تر براؤزر آپ کو کوکیز روکنے یا حذف کرنے کی اجازت دیتے ہیں۔ لازمی کوکیز روکنے سے ویب سائٹ کے کچھ حصے، بشمول آن لائن آرڈرنگ، صحیح کام نہیں کر سکیں گے۔",
  "13. رضامندی اور اس کی واپسی",
  "جہاں قانون تقاضا کرے، ہم غیر ضروری کوکیز رکھنے سے پہلے رضامندی لیتے ہیں۔ رضامندی کوکی ترجیحات کے مرکز یا براؤزر کی ترتیبات سے کسی بھی وقت واپس لی جا سکتی ہے۔",
  "14. معلومات کا اشتراک",
  "ہم کوکی سے متعلق معلومات ان قابلِ اعتماد سروس فراہم کنندگان کے ساتھ بانٹ سکتے ہیں جو ہماری ویب سائٹ چلانے یا آن لائن آرڈر پروسیس کرنے میں مدد دیتے ہیں، بشمول Toast، یا جہاں قانون تقاضا کرے۔ ہم کوکیز کے ذریعے جمع کی گئی ذاتی معلومات فروخت نہیں کرتے۔",
  "15. تبدیلیاں",
  "ہم یہ کوکی پالیسی وقتاً فوقتاً اپ ڈیٹ کر سکتے ہیں۔ اہم تبدیلیاں آخری اپ ڈیٹ کی تاریخ بدل کر ظاہر کی جائیں گی۔",
  "16. رابطے کی معلومات",
  "Corner Bagel، Public Entity Holdings کے زیرِ انتظام۔ ای میل: {email}",
  "اگر اس کوکی پالیسی یا اپنے رازداری کے حقوق کے بارے میں کوئی سوال ہو تو اوپر دیے گئے ای میل پر ہم سے رابطہ کریں۔",
];

const urPrivacy = [
  "رازداری کی پالیسی",
  "نافذ العمل تاریخ: 8 جولائی 2026",
  "Corner Bagel (“Corner Bagel”، “ہم”، “ہمارا”) میں ہم آپ کی رازداری کا احترام کرتے ہیں۔ یہ پالیسی بتاتی ہے کہ جب آپ ہماری ویب سائٹ دیکھتے ہیں، آرڈر دیتے ہیں، ہماری میلنگ لسٹ میں شامل ہوتے ہیں، پروموشنز میں حصہ لیتے ہیں یا کسی اور طرح ہمارے کاروبار سے رابطہ کرتے ہیں تو ہم معلومات کیسے جمع، استعمال، ظاہر اور محفوظ کرتے ہیں۔",
  "ہماری ویب سائٹ یا خدمات استعمال کر کے آپ اس رازداری کی پالیسی سے اتفاق کرتے ہیں۔",
  "ہم کون سی معلومات جمع کرتے ہیں",
  "وہ معلومات جو آپ دیتے ہیں",
  "ہم یہ جمع کر سکتے ہیں:",
  "نام",
  "ای میل ایڈریس",
  "فون نمبر",
  "بلنگ اور ادائیگی کی معلومات",
  "ترسیل یا پک اپ کی معلومات",
  "آرڈر کی تاریخ",
  "لائلٹی یا ریوارڈز اکاؤنٹ کی معلومات (اگر لاگو ہو)",
  "خودکار طور پر جمع ہونے والی معلومات",
  "جب آپ ہماری ویب سائٹ پر آتے ہیں تو ہم یہ جمع کر سکتے ہیں:",
  "IP ایڈریس",
  "براؤزر کی قسم",
  "آلے کی معلومات",
  "آپریٹنگ سسٹم",
  "دیکھے گئے صفحات",
  "ہماری ویب سائٹ پر گزارا گیا وقت",
  "حوالہ دینے والی ویب سائٹس",
  "کوکیز اور اس جیسی ٹیکنالوجیز",
  "ہم آپ کی معلومات کیسے استعمال کرتے ہیں",
  "ہم آپ کی معلومات اس لیے استعمال کرتے ہیں:",
  "آرڈر لینے اور پورے کرنے کے لیے",
  "آپ کے آرڈر کے بارے میں رابطہ کرنے کے لیے",
  "کسٹمر سپورٹ فراہم کرنے کے لیے",
  "اپنی مصنوعات اور خدمات بہتر بنانے کے لیے",
  "آپ کا تجربہ ذاتی نوعیت کا بنانے کے لیے",
  "نیوز لیٹر، پروموشنز اور خاص پیشکشیں بھیجنے کے لیے (جب آپ رضامندی دیں)",
  "لائلٹی یا ریوارڈز پروگرام چلانے کے لیے",
  "دھوکہ دہی روکنے اور سیکیورٹی برقرار رکھنے کے لیے",
  "قانونی ذمہ داریاں پوری کرنے کے لیے",
  "مارکیٹنگ کے پیغامات",
  "اگر آپ ہماری میلنگ لسٹ میں شامل ہوں تو ہم ان کے بارے میں اپ ڈیٹ بھیج سکتے ہیں:",
  "مینو کی نئی اشیاء",
  "موسمی پیشکشیں",
  "پروموشنز",
  "تقریبات",
  "دکان کے اعلانات",
  "آپ ہماری ای میلز میں شامل ان سبسکرائب لنک سے کسی بھی وقت رکنیت ختم کر سکتے ہیں۔",
  "کوکیز اور ٹریکنگ",
  "ہماری ویب سائٹ کوکیز اور اس جیسی ٹیکنالوجیز اس لیے استعمال کر سکتی ہے:",
  "صارف کی ترجیحات یاد رکھنے کے لیے",
  "ویب سائٹ کی کارکردگی بہتر کرنے کے لیے",
  "ویب سائٹ کی ٹریفک کا تجزیہ کرنے کے لیے",
  "مارکیٹنگ کی مؤثریت ناپنے کے لیے",
  "زیادہ تر براؤزر آپ کو ترتیبات سے کوکیز بند کرنے کی اجازت دیتے ہیں، اگرچہ ایسا کرنے سے ویب سائٹ کی کچھ خصوصیات متاثر ہو سکتی ہیں۔",
  "ادائیگی کی معلومات",
  "ادائیگیاں قابلِ اعتماد بیرونی ادائیگی فراہم کنندگان کے ذریعے پروسیس ہوتی ہیں۔",
  "Corner Bagel ادائیگی کارڈ کے مکمل نمبر اپنے سرورز پر محفوظ نہیں کرتا۔",
  "معلومات کا اشتراک",
  "ہم آپ کی ذاتی معلومات فروخت نہیں کرتے۔",
  "ہم اپنے کاروبار کو چلانے میں مدد دینے والے قابلِ اعتماد سروس فراہم کنندگان کے ساتھ معلومات بانٹ سکتے ہیں، بشمول:",
  "ادائیگی پروسیسر",
  "آن لائن آرڈرنگ فراہم کنندگان",
  "ترسیل کے شراکت دار",
  "ای میل مارکیٹنگ پلیٹ فارم",
  "ویب سائٹ ہوسٹنگ فراہم کنندگان",
  "تجزیاتی فراہم کنندگان",
  "یہ فراہم کنندگان آپ کی معلومات صرف ہماری جانب سے خدمات انجام دینے کے لیے استعمال کر سکتے ہیں۔ ہم قانون کے تقاضے پر یا اپنے قانونی حقوق کے تحفظ کے لیے بھی معلومات ظاہر کر سکتے ہیں۔",
  "ڈیٹا کی حفاظت",
  "ہم آپ کی معلومات کے تحفظ کے لیے تجارتی طور پر معقول انتظامی، تکنیکی اور طبعی حفاظتی اقدامات کرتے ہیں۔",
  "اگرچہ ہم آپ کی معلومات کے تحفظ کی کوشش کرتے ہیں، لیکن الیکٹرانک ترسیل یا ذخیرہ کرنے کا کوئی طریقہ مکمل طور پر محفوظ نہیں ہوتا۔",
  "ڈیٹا کی مدت",
  "ہم ذاتی معلومات صرف اتنی دیر رکھتے ہیں جتنی ان کے لیے ضروری ہو:",
  "آرڈر پورے کرنا",
  "درخواست کردہ خدمات فراہم کرنا",
  "قانونی اور اکاؤنٹنگ تقاضے پورے کرنا",
  "تنازعات حل کرنا",
  "اپنے معاہدوں پر عمل کرانا",
  "آپ کے رازداری کے حقوق",
  "آپ کی ریاست یا ملک کے مطابق آپ کو اپنی ذاتی معلومات کے بارے میں یہ حقوق حاصل ہو سکتے ہیں:",
  "اپنی معلومات تک رسائی",
  "غلط معلومات درست کرانا",
  "ذاتی معلومات حذف کرنے کی درخواست",
  "اپنی معلومات کی نقل کی درخواست",
  "کچھ مارکیٹنگ پیغامات سے دستبرداری",
  "ان حقوق کے استعمال کے لیے ہم سے {email} پر رابطہ کریں۔",
  "ملازمت کے درخواست دہندگان",
  "اگر آپ ہمارے ہاں ملازمت کی درخواست دیتے ہیں تو ہم وہ معلومات جمع کرتے ہیں جو آپ درخواست فارم میں لکھتے ہیں: آپ کا نام اور رابطے کی تفصیلات، آپ جس شہر میں رہتے ہیں، جو عہدے اور اوقات آپ منتخب کرتے ہیں، جو تعلیم، تجربہ اور حوالہ جات آپ شامل کرنا چاہیں، اور آپ کے تحریری جواب۔ ہم یہ صرف اس فیصلے کے لیے استعمال کرتے ہیں کہ آپ کو انٹرویو کے لیے بلایا جائے یا نہیں، اور کسی اور کام کے لیے نہیں۔",
  "ہم درخواست دہندگان سے نسل، مذہب، عمر، معذوری، قومیت، جنس، جنسی رجحان، ازدواجی حیثیت یا فوجی خدمت کے بارے میں نہیں پوچھتے اور نہ انہیں مدِنظر رکھتے ہیں۔ ہم اس فارم کے ذریعے پس منظر کی جانچ نہیں کرتے۔ اگر کبھی پس منظر کی جانچ بھرتی کا حصہ بنی تو ہم وفاقی قانون کے مطابق اس کی اجازت الگ سے اور تحریری طور پر مانگیں گے۔",
  "درخواستیں ایک دستاویز کی صورت میں ہمارے بھرتی کے ای میل پر آتی ہیں۔ انہیں کسی گاہک ڈیٹابیس میں شامل نہیں کیا جاتا اور نہ مارکیٹنگ کے لیے استعمال ہوتا ہے۔ ہم انہیں زیادہ سے زیادہ ایک سال رکھتے ہیں، پھر حذف کر دیتے ہیں۔ درخواست دہندگان کو وہی حقوق حاصل ہیں جو اوپر بیان ہوئے — رسائی، درستی، حذف اور نقل — اور وہ {email} پر لکھ کر انہیں استعمال کر سکتے ہیں۔",
  "جب تک آپ فارم بھر رہے ہوتے ہیں، ایک نامکمل مسودہ آپ کے اپنے براؤزر میں محفوظ رہتا ہے تاکہ آپ واپس آ کر مکمل کر سکیں۔ یہ ہمیں نہیں بھیجا جاتا، جمع کرانے پر یا پندرہ منٹ تک چھوڑ دینے پر حذف ہو جاتا ہے، اور «نئے سرے سے شروع کریں» اسے فوراً مٹا دیتا ہے۔ اگر آپ انگریزی کے علاوہ کسی زبان میں لکھتے ہیں تو ہم پڑھنے کے لیے ترجمہ کرتے ہیں، اور آپ کے اصل الفاظ ترجمے کے ساتھ محفوظ رکھتے ہیں۔",
  "بچوں کی رازداری",
  "ہماری خدمات 13 سال سے کم عمر بچوں کے لیے نہیں ہیں اور ہم جان بوجھ کر بچوں سے ذاتی معلومات جمع نہیں کرتے۔ اگر ہمیں معلوم ہو کہ مناسب رضامندی کے بغیر کسی بچے کی معلومات جمع کی گئی ہیں تو ہم انہیں فوراً حذف کر دیں گے۔",
  "تیسرے فریق کے لنکس",
  "ہماری ویب سائٹ پر تیسرے فریق کی ویب سائٹس یا خدمات کے لنکس ہو سکتے ہیں۔ ہم ان تیسرے فریقوں کی رازداری کی روش یا مواد کے ذمہ دار نہیں ہیں۔",
  "اپ ڈیٹس",
  "ہم اس رازداری کی پالیسی کو وقتاً فوقتاً اپ ڈیٹ کر سکتے ہیں۔ تبدیلی کی صورت میں ہم اوپر دی گئی نافذ العمل تاریخ بدل دیں گے۔ اپ ڈیٹ کے بعد خدمات کا استعمال جاری رکھنا نظرثانی شدہ پالیسی کی قبولیت سمجھا جائے گا۔",
  "رابطہ",
  "Corner Bagel۔ ای میل: {email}",
];

// ——— Japanese ———

const jaCookie = [
  "クッキーポリシー",
  "運営: Public Entity Holdings",
  "最終更新日: 2026年8月1日",
  "1. はじめに",
  "本クッキーポリシーは、Public Entity Holdings が運営する Corner Bagel（以下「Corner Bagel」「当店」）が、当ウェブサイトでクッキーおよび類似の追跡技術をどのように使用するかを説明するものです。当店の{privacyPolicy}と併せてお読みください。",
  "本ポリシーは、カリフォルニア州を含む米国内で当ウェブサイトをご利用の方を対象としています。カリフォルニア州プライバシー権利法（CPRA）により改正されたカリフォルニア州消費者プライバシー法（CCPA）を含む適用法令で求められる場合、当店は必須でないクッキーを設置する前に同意を取得します。",
  "2. クッキーとは",
  "クッキーとは、当ウェブサイトをご覧になった際にお使いの端末に保存される小さなテキストファイルです。端末の識別、設定の記憶、機能の改善、オンライン注文の提供に役立ちます。クッキーにはセッションクッキーと永続クッキーがあり、当店が設置するものと第三者が設置するものがあります。",
  "3. クッキーの利用目的",
  "当店は、ウェブサイトが正しく安全に動作するため、お客様の設定を記憶するため、体験を個別化するため、（将来有効にした場合）ウェブサイトの性能を分析するため、そして Toast が提供するものを含むオンライン注文サービスを提供するためにクッキーを使用します。お客様がご依頼のサービスを完了するために必要な範囲を超えて、機微な個人情報をクッキーで収集することはありません。",
  "4. 使用するクッキーの種類",
  "必須クッキー",
  "セキュリティ、セッション管理、不正防止、決済、ウェブサイトの動作に不可欠です。同意は不要です。",
  "機能クッキー",
  "アクセシビリティ設定や注文に関する設定を記憶します。該当する場合は同意が必要です。",
  "分析クッキー",
  "現在は使用していません。導入する場合はウェブサイトの利用状況の把握に用い、同意を得たうえでのみ有効化します。",
  "広告・マーケティングクッキー",
  "Corner Bagel は現在、広告またはマーケティング目的のクッキーを使用していません。",
  "5. 必須クッキー",
  "これらのクッキーは、ウェブサイトの閲覧、メニューの表示、お問い合わせフォームの送信、オンライン注文の完了に必要です。これらがない場合、ご依頼のサービスを提供できません。",
  "6. 機能クッキー",
  "機能クッキーはお客様の設定を記憶し、体験を向上させます。これらのクッキーが他のウェブサイトでの行動を追跡することはなく、法令が認める範囲でのみ使用します。",
  "7. 分析クッキー",
  "Corner Bagel は現在、分析クッキーを使用していません。将来的に分析ツールを追加する場合は、ご利用の方にお知らせし、有効化の前に同意いただく機会を設けます。",
  "8. 広告・マーケティングクッキー",
  "Corner Bagel は現在、広告やリターゲティングのクッキーを設置していません。クッキーで収集した個人情報を広告目的で販売することはありません。",
  "9. 第三者のクッキー",
  "当ウェブサイトは、オンライン注文のための Toast を含む第三者のサービスを利用する場合があります。これらの提供事業者は、各社のプライバシーポリシーおよびクッキーポリシーに従って独自のクッキーを設置することがあります。",
  "10. Toast での注文",
  "Toast が提供するオンライン注文プラットフォームをご利用の際、Toast は注文機能の動作に必要なクッキーを設置することがあります。Toast のプライバシーおよびクッキーの取り扱いは Toast 自身のポリシーに従います。ご注文の前にそれらのポリシーをご確認いただくことをおすすめします。",
  "11. クッキー設定の管理",
  "当店のクッキーバナーから、必須でないクッキーを受け入れる、拒否する、または個別に設定することができます。設定はいつでも変更できます。",
  "12. ブラウザの設定",
  "ほとんどのブラウザではクッキーをブロックまたは削除できます。必須クッキーをブロックすると、オンライン注文を含むウェブサイトの一部が正しく動作しなくなることがあります。",
  "13. 同意と撤回",
  "法令で求められる場合、当店は必須でないクッキーを設置する前に同意を取得します。同意は、クッキー設定センターまたはブラウザの設定からいつでも撤回できます。",
  "14. 情報の共有",
  "当店は、ウェブサイトの運営やオンライン注文の処理を支援する信頼できるサービス提供事業者（Toast を含む）と、または法令で求められる場合に、クッキーに関する情報を共有することがあります。クッキーで収集した個人情報を販売することはありません。",
  "15. 変更",
  "当店は本クッキーポリシーを随時更新することがあります。重要な変更は、最終更新日を改めることで反映します。",
  "16. お問い合わせ",
  "Corner Bagel（運営: Public Entity Holdings）。メール: {email}",
  "本クッキーポリシーやお客様のプライバシーに関する権利についてご質問がある場合は、上記のメールアドレスまでご連絡ください。",
];

const jaPrivacy = [
  "プライバシーポリシー",
  "発効日: 2026年7月8日",
  "Corner Bagel（以下「Corner Bagel」「当店」）は、お客様のプライバシーを尊重します。本ポリシーは、お客様が当ウェブサイトをご覧になる、ご注文いただく、メーリングリストにご登録いただく、キャンペーンにご参加いただく、その他当店と関わりを持たれる際に、当店がどのように情報を収集・利用・開示・保護するかを説明するものです。",
  "当ウェブサイトまたは当店のサービスをご利用いただくことで、本プライバシーポリシーに同意いただいたものとみなします。",
  "収集する情報",
  "お客様からご提供いただく情報",
  "以下を収集する場合があります:",
  "お名前",
  "メールアドレス",
  "電話番号",
  "請求および支払いに関する情報",
  "配達または受け取りに関する情報",
  "注文履歴",
  "ポイントまたはリワードのアカウント情報（該当する場合）",
  "自動的に収集される情報",
  "当ウェブサイトをご覧になった際、以下を収集する場合があります:",
  "IP アドレス",
  "ブラウザの種類",
  "端末情報",
  "オペレーティングシステム",
  "閲覧したページ",
  "当ウェブサイトの滞在時間",
  "参照元のウェブサイト",
  "クッキーおよび類似技術",
  "情報の利用方法",
  "当店は以下の目的でお客様の情報を利用します:",
  "ご注文の処理とお届け",
  "ご注文に関するご連絡",
  "カスタマーサポートの提供",
  "商品とサービスの改善",
  "体験の個別化",
  "ニュースレター、キャンペーン、特別なご案内の送付（ご登録いただいた場合）",
  "ポイントまたはリワードプログラムの運営",
  "不正の防止とセキュリティの維持",
  "法令上の義務の遵守",
  "マーケティングのご連絡",
  "メーリングリストにご登録いただいた場合、以下に関するお知らせをお送りすることがあります:",
  "新しいメニュー",
  "季節限定の商品",
  "キャンペーン",
  "イベント",
  "店舗からのお知らせ",
  "配信はいつでも、メールに記載の配信停止リンクから解除できます。",
  "クッキーと追跡",
  "当ウェブサイトは、以下の目的でクッキーおよび類似技術を使用する場合があります:",
  "ご利用者の設定の記憶",
  "ウェブサイトの機能の改善",
  "ウェブサイトのアクセス状況の分析",
  "マーケティング効果の測定",
  "ほとんどのブラウザでは設定からクッキーを無効にできますが、その場合ウェブサイトの一部機能に影響が出ることがあります。",
  "お支払い情報",
  "お支払いは、信頼できる外部の決済事業者を通じて処理されます。",
  "Corner Bagel は、支払いカードの完全な番号を当店のサーバーに保存しません。",
  "情報の共有",
  "当店はお客様の個人情報を販売しません。",
  "当店は、事業の運営を支援する信頼できるサービス提供事業者と情報を共有する場合があります。これには次が含まれます:",
  "決済事業者",
  "オンライン注文の提供事業者",
  "配達のパートナー",
  "メールマーケティングのプラットフォーム",
  "ウェブサイトのホスティング事業者",
  "分析サービスの提供事業者",
  "これらの事業者は、当店に代わってサービスを提供する目的でのみお客様の情報を利用できます。また、法令で求められる場合や当店の法的権利を守るために情報を開示することがあります。",
  "情報の安全管理",
  "当店は、お客様の情報を保護するために、商業的に合理的な管理的・技術的・物理的な安全管理措置を実施しています。",
  "情報の保護に努めていますが、電子的な送信または保存の方法で完全に安全なものはありません。",
  "情報の保存期間",
  "当店は、以下に必要な期間に限り個人情報を保存します:",
  "ご注文のお届け",
  "ご依頼のサービスの提供",
  "法令および会計上の要件への対応",
  "紛争の解決",
  "当店の契約の履行",
  "お客様のプライバシーに関する権利",
  "お住まいの州または国によっては、個人情報について以下の権利をお持ちの場合があります:",
  "ご自身の情報へのアクセス",
  "誤った情報の訂正",
  "個人情報の削除の請求",
  "ご自身の情報の写しの請求",
  "一部のマーケティング配信の停止",
  "これらの権利の行使をご希望の場合は、{email} までご連絡ください。",
  "採用応募者の方へ",
  "採用にご応募いただいた場合、応募フォームにご入力いただいた内容を取得します。お名前と連絡先、お住まいの市区町村、選択された職種と勤務可能な時間、ご自身で追加された学歴・職歴・推薦者、そしてご記入いただいた回答です。面接を行うかどうかの判断にのみ使用し、それ以外には使用しません。",
  "応募者の方に、人種、宗教、年齢、障害、出身国、性別、性的指向、婚姻状況、兵役の有無をお尋ねすることはなく、考慮もしません。このフォームで身元調査を行うことはありません。今後、身元調査が採用手続きの一部となる場合は、連邦法の定めに従い、別途書面で同意をお願いします。",
  "応募内容は書類として当店の採用用メールアドレスに届きます。顧客データベースに追加されることはなく、マーケティングにも使用しません。最長1年間保管したのち削除します。応募者の方にも上記と同じ権利（開示、訂正、削除、写しの請求）があり、{email} までご連絡いただくことで行使できます。",
  "入力中は、未完成の下書きがお使いのブラウザに保存され、続きから再開できます。当店には送られず、送信時、または15分そのままにすると削除され、「最初から」を押せばその場で消えます。英語以外の言語でご記入いただいた場合は、読めるよう翻訳し、実際に書かれた文面も翻訳と並べて保管します。",
  "お子様のプライバシー",
  "当店のサービスは 13 歳未満のお子様を対象としておらず、お子様の個人情報を意図して収集することはありません。適切な同意なくお子様の情報が収集されたことが判明した場合は、速やかに削除します。",
  "第三者へのリンク",
  "当ウェブサイトには、第三者のウェブサイトやサービスへのリンクが含まれる場合があります。当店は、それら第三者のプライバシーの取り扱いや内容について責任を負いません。",
  "更新",
  "当店は本プライバシーポリシーを随時更新することがあります。変更があった場合は、上記の発効日を改めます。更新後もサービスをご利用いただくことで、改定後のポリシーに同意いただいたものとみなします。",
  "お問い合わせ",
  "Corner Bagel。メール: {email}",
];

// ——— Chinese (Simplified) ———

const zhCookie = [
  "Cookie 政策",
  "由 Public Entity Holdings 运营",
  "最后更新：2026 年 8 月 1 日",
  "1. 引言",
  "本 Cookie 政策说明由 Public Entity Holdings 运营的 Corner Bagel（以下称“Corner Bagel”“我们”）如何在本网站使用 Cookie 及类似的追踪技术。本政策应与我们的{privacyPolicy}一并阅读。",
  "本政策面向在美国（含加利福尼亚州）使用本网站的访问者。在适用法律要求的情况下，包括经《加州隐私权法案》（CPRA）修订的《加州消费者隐私法案》（CCPA），我们会在放置非必要 Cookie 之前取得同意。",
  "2. 什么是 Cookie？",
  "Cookie 是您访问本网站时保存在您设备上的小型文本文件。它们用于识别您的设备、记住偏好设置、改进功能，并支持在线点餐。Cookie 可以是会话 Cookie 或持久 Cookie，也可以是第一方或第三方 Cookie。",
  "3. 我们如何使用 Cookie",
  "我们使用 Cookie 是为了让网站正确、安全地运行；记住您的偏好设置；为您提供个性化体验；分析网站性能（如未来启用）；以及支持在线点餐服务，包括由 Toast 提供的服务。除了完成您所请求的服务所必需的范围之外，我们不会使用 Cookie 收集敏感个人信息。",
  "4. 我们使用的 Cookie 类别",
  "严格必要",
  "对安全、会话管理、防欺诈、结账和网站功能不可或缺。无需征得同意。",
  "功能性",
  "记住无障碍设置和点餐偏好。在适用情况下需要征得同意。",
  "分析类",
  "目前未启用。若日后引入，将用于帮助我们了解网站使用情况，并且只有在取得同意后才会启用。",
  "广告/营销",
  "Corner Bagel 目前不使用广告或营销类 Cookie。",
  "5. 严格必要的 Cookie",
  "这些 Cookie 是浏览网站、查看菜单、提交联系表单和完成在线订单所必需的。没有它们，我们无法提供您所请求的服务。",
  "6. 功能性 Cookie",
  "功能性 Cookie 会记住您的偏好并改善您的体验。这些 Cookie 不会跨其他网站追踪您的行为，且仅在法律允许的范围内使用。",
  "7. 分析类 Cookie",
  "Corner Bagel 目前不使用分析类 Cookie。若日后添加分析工具，我们会通知访问者，并在启用前提供表示同意的机会。",
  "8. 广告与营销 Cookie",
  "Corner Bagel 目前不放置广告或再营销 Cookie。我们不会为广告目的出售通过 Cookie 收集的个人信息。",
  "9. 第三方 Cookie",
  "本网站可能使用第三方服务，包括用于在线点餐的 Toast。这些服务提供方可能会依据其自身的隐私和 Cookie 政策放置自己的 Cookie。",
  "10. Toast 点餐",
  "当您使用由 Toast 提供的在线点餐平台时，Toast 可能会放置运行点餐所必需的 Cookie。Toast 的隐私与 Cookie 做法受 Toast 自身政策约束。Corner Bagel 建议顾客在下单前阅读这些政策。",
  "11. 管理 Cookie 偏好",
  "您可以通过我们的 Cookie 横幅接受、拒绝或自定义非必要 Cookie。偏好设置可随时更改。",
  "12. 浏览器控制",
  "大多数浏览器都允许您阻止或删除 Cookie。阻止严格必要的 Cookie 可能会导致网站的部分功能（包括在线点餐）无法正常运行。",
  "13. 同意与撤回",
  "在法律要求的情况下，我们会在放置非必要 Cookie 之前取得同意。您可以随时通过 Cookie 偏好中心或浏览器设置撤回同意。",
  "14. 数据共享",
  "我们可能会与协助运营本网站或处理在线订单的可信服务提供方（包括 Toast）共享与 Cookie 相关的信息，或在法律要求时共享。我们不会出售通过 Cookie 收集的个人信息。",
  "15. 变更",
  "我们可能会不时更新本 Cookie 政策。重大变更将通过更新“最后更新”日期来体现。",
  "16. 联系方式",
  "Corner Bagel，由 Public Entity Holdings 运营。邮箱：{email}",
  "如果您对本 Cookie 政策或您的隐私权利有疑问，请通过上述邮箱与我们联系。",
];

const zhPrivacy = [
  "隐私政策",
  "生效日期：2026 年 7 月 8 日",
  "在 Corner Bagel（以下称“Corner Bagel”“我们”），我们尊重您的隐私。本政策说明当您访问本网站、下单、加入我们的邮件列表、参与促销活动或以其他方式与我们的业务往来时，我们如何收集、使用、披露和保护信息。",
  "使用本网站或我们的服务，即表示您同意本隐私政策。",
  "我们收集的信息",
  "您提供的信息",
  "我们可能收集：",
  "姓名",
  "电子邮箱地址",
  "电话号码",
  "账单和付款信息",
  "配送或自取信息",
  "订单记录",
  "会员或积分账户信息（如适用）",
  "自动收集的信息",
  "当您访问本网站时，我们可能收集：",
  "IP 地址",
  "浏览器类型",
  "设备信息",
  "操作系统",
  "浏览过的页面",
  "在本网站停留的时间",
  "来源网站",
  "Cookie 及类似技术",
  "我们如何使用您的信息",
  "我们使用您的信息用于：",
  "处理并完成订单",
  "就您的订单与您联系",
  "提供客户支持",
  "改进我们的产品和服务",
  "为您提供个性化体验",
  "发送电子报、促销和特别优惠（在您选择接收时）",
  "运营会员或积分计划",
  "防范欺诈并维护安全",
  "遵守法律义务",
  "营销通讯",
  "如果您订阅了我们的邮件列表，我们可能会发送以下方面的更新：",
  "新菜品",
  "季节限定",
  "促销活动",
  "活动",
  "门店公告",
  "您可以随时点击我们邮件中的退订链接取消订阅。",
  "Cookie 与追踪",
  "本网站可能使用 Cookie 及类似技术，用于：",
  "记住用户偏好",
  "改进网站功能",
  "分析网站流量",
  "衡量营销效果",
  "大多数浏览器都允许您在设置中禁用 Cookie，但这样做可能会影响网站的某些功能。",
  "付款信息",
  "付款由可信的第三方支付服务商处理。",
  "Corner Bagel 不会在我们的服务器上存储完整的支付卡号。",
  "信息的共享",
  "我们不会出售您的个人信息。",
  "我们可能会与协助我们经营业务的可信服务提供方共享信息，包括：",
  "支付处理方",
  "在线点餐服务提供方",
  "配送合作伙伴",
  "邮件营销平台",
  "网站托管服务商",
  "分析服务提供方",
  "这些服务提供方只能为代表我们提供服务而使用您的信息。在法律要求时，或为保护我们的合法权利时，我们也可能披露信息。",
  "数据安全",
  "我们采取商业上合理的管理、技术和物理保护措施来保护您的信息。",
  "尽管我们努力保护您的信息，但没有任何电子传输或存储方式是绝对安全的。",
  "数据保留",
  "我们仅在以下用途所必需的期限内保留个人信息：",
  "完成订单",
  "提供您请求的服务",
  "满足法律和会计要求",
  "解决争议",
  "执行我们的协议",
  "您的隐私权利",
  "根据您所在的州或国家/地区，您可能对自己的个人信息享有以下权利：",
  "访问您的信息",
  "更正不准确的信息",
  "要求删除个人信息",
  "要求获取您信息的副本",
  "退出特定的营销通讯",
  "如需行使这些权利，请通过 {email} 与我们联系。",
  "求职申请人",
  "如果你向我们求职，我们会收集你在申请表里填写的内容：姓名和联系方式、居住城市、你勾选的岗位和可上班时间、你自愿填写的教育经历、工作经历和推荐人，以及你写下的回答。我们只用它来决定是否请你来面谈，不作他用。",
  "我们不会询问求职者的种族、宗教、年龄、身体状况、原籍国、性别、性取向、婚姻状况或退伍军人身份，也不会将这些纳入考虑。我们不会通过这份表格做背景调查。如果背景调查日后成为招聘流程的一部分，我们会依照联邦法律另行以书面形式征求你的授权。",
  "申请会以文档形式发送到我们的招聘邮箱，不会进入任何客户数据库，也不会用于营销。我们最多保留一年，之后删除。求职者享有上文所述的同样权利——查阅、更正、删除和索取副本——可写信至 {email} 行使。",
  "在你填写期间，未完成的草稿会保存在你自己的浏览器里，方便你回来接着填。它不会发给我们，在你提交时或搁置十五分钟后删除，点“重新开始”会立即清除。如果你用英语以外的语言作答，我们会翻译成英文以便阅读，并且会把你原本写的内容一并保留。",
  "儿童隐私",
  "我们的服务不面向 13 岁以下儿童，我们也不会在知情的情况下收集儿童的个人信息。如果我们发现在未获得适当同意的情况下收集了儿童的信息，会立即删除。",
  "第三方链接",
  "本网站可能包含指向第三方网站或服务的链接。我们不对这些第三方的隐私做法或内容负责。",
  "更新",
  "我们可能会不时更新本隐私政策。发生变更时，我们会修改上方的生效日期。更新后继续使用我们的服务即表示接受修订后的政策。",
  "联系方式",
  "Corner Bagel。邮箱：{email}",
];

// ——— Burmese ———

const myCookie = [
  "ကွတ်ကီး မူဝါဒ",
  "Public Entity Holdings မှ လုပ်ငန်းလည်ပတ်သည်",
  "နောက်ဆုံး မွမ်းမံသည့်ရက်− ၂၀၂၆ ခုနှစ် သြဂုတ်လ ၁ ရက်",
  "၁။ နိဒါန်း",
  "ဤကွတ်ကီးမူဝါဒသည် Public Entity Holdings မှ လုပ်ငန်းလည်ပတ်သော Corner Bagel (“Corner Bagel”၊ “ကျွန်ုပ်တို့”) က ဝဘ်ဆိုက်ပေါ်တွင် ကွတ်ကီးများနှင့် အလားတူ ခြေရာခံနည်းပညာများကို မည်သို့အသုံးပြုသည်ကို ရှင်းပြပါသည်။ ဤမူဝါဒကို ကျွန်ုပ်တို့၏ {privacyPolicy} နှင့်အတူ ဖတ်ရှုပါ။",
  "ဤမူဝါဒသည် ကယ်လီဖိုးနီးယားအပါအဝင် အမေရိကန်ပြည်ထောင်စုအတွင်း ကျွန်ုပ်တို့၏ ဝဘ်ဆိုက်ကို အသုံးပြုသူများအတွက် ဖြစ်ပါသည်။ California Privacy Rights Act (CPRA) ဖြင့် ပြင်ဆင်ထားသော California Consumer Privacy Act (CCPA) အပါအဝင် သက်ဆိုင်ရာဥပဒေက လိုအပ်သည့်အခါ မလိုအပ်သော ကွတ်ကီးများ မထည့်မီ သဘောတူညီချက် ရယူပါမည်။",
  "၂။ ကွတ်ကီးဆိုသည်မှာ အဘယ်နည်း",
  "ကွတ်ကီးများသည် ကျွန်ုပ်တို့၏ ဝဘ်ဆိုက်သို့ ဝင်ရောက်သည့်အခါ သင့်စက်ပစ္စည်းတွင် သိမ်းဆည်းခံရသော စာသားဖိုင်ငယ်များ ဖြစ်သည်။ ၎င်းတို့သည် သင့်စက်ကို မှတ်မိစေရန်၊ ရွေးချယ်မှုများကို မှတ်ထားရန်၊ လုပ်ဆောင်ချက်များ ပိုမိုကောင်းမွန်စေရန်နှင့် အွန်လိုင်း အော်ဒါမှာယူမှုကို ပံ့ပိုးရန် ကူညီပေးသည်။ ကွတ်ကီးများသည် session ကွတ်ကီး သို့မဟုတ် အမြဲတမ်း ကွတ်ကီး ဖြစ်နိုင်ပြီး၊ ကိုယ်ပိုင် သို့မဟုတ် တတိယအဖွဲ့အစည်း၏ ကွတ်ကီး ဖြစ်နိုင်ပါသည်။",
  "၃။ ကွတ်ကီးများကို မည်သို့ အသုံးပြုသနည်း",
  "ကျွန်ုပ်တို့သည် ဝဘ်ဆိုက် မှန်ကန်စွာနှင့် လုံခြုံစွာ အလုပ်လုပ်စေရန်၊ သင့်ရွေးချယ်မှုများကို မှတ်ထားရန်၊ သင့်အတွေ့အကြုံကို ကိုယ်ပိုင်ပုံစံဖြစ်စေရန်၊ (နောင်တွင် ဖွင့်လျှင်) ဝဘ်ဆိုက်စွမ်းဆောင်ရည်ကို ခွဲခြမ်းစိတ်ဖြာရန်နှင့် Toast မှ ပံ့ပိုးသည့်အရာများအပါအဝင် အွန်လိုင်း အော်ဒါဝန်ဆောင်မှုများကို ပံ့ပိုးရန် ကွတ်ကီးများကို အသုံးပြုပါသည်။ သင်တောင်းဆိုသော ဝန်ဆောင်မှုများ ပြီးမြောက်ရန် လိုအပ်သည်ထက် ကျော်လွန်၍ အထိခိုက်မခံသော ကိုယ်ရေးအချက်အလက်များ စုဆောင်းရန် ကွတ်ကီးများကို မသုံးပါ။",
  "၄။ ကျွန်ုပ်တို့ အသုံးပြုသော ကွတ်ကီး အမျိုးအစားများ",
  "မဖြစ်မနေ လိုအပ်သော",
  "လုံခြုံရေး၊ session စီမံခန့်ခွဲမှု၊ လိမ်လည်မှု ကာကွယ်ရေး၊ ငွေပေးချေမှုနှင့် ဝဘ်ဆိုက် လုပ်ဆောင်ချက်များအတွက် မရှိမဖြစ် လိုအပ်သည်။ သဘောတူညီချက် မလိုအပ်ပါ။",
  "လုပ်ဆောင်ချက်ဆိုင်ရာ",
  "အသုံးပြုနိုင်စွမ်း ဆက်တင်များနှင့် အော်ဒါဆိုင်ရာ ရွေးချယ်မှုများကို မှတ်ထားသည်။ သက်ဆိုင်ရာအခါတွင် သဘောတူညီချက် လိုအပ်သည်။",
  "ခွဲခြမ်းစိတ်ဖြာမှုဆိုင်ရာ",
  "လက်ရှိတွင် အသုံးမပြုပါ။ မိတ်ဆက်ပါက ဝဘ်ဆိုက် အသုံးပြုမှုကို နားလည်ရန် ကူညီမည်ဖြစ်ပြီး၊ သဘောတူညီချက် ရရှိပြီးမှသာ ဖွင့်ပါမည်။",
  "ကြော်ငြာ/စျေးကွက်ရှာဖွေရေး",
  "Corner Bagel သည် လက်ရှိတွင် ကြော်ငြာ သို့မဟုတ် စျေးကွက်ရှာဖွေရေး ကွတ်ကီးများ မသုံးပါ။",
  "၅။ မဖြစ်မနေ လိုအပ်သော ကွတ်ကီးများ",
  "ဤကွတ်ကီးများသည် ဝဘ်ဆိုက်ကြည့်ရှုခြင်း၊ မီနူးများ ကြည့်ခြင်း၊ ဆက်သွယ်ရန်ဖောင် ပေးပို့ခြင်းနှင့် အွန်လိုင်း အော်ဒါများ ပြီးမြောက်စေခြင်းအတွက် လိုအပ်ပါသည်။ ၎င်းတို့မပါဘဲ တောင်းဆိုထားသော ဝန်ဆောင်မှုများကို ပေးအပ်၍ မရပါ။",
  "၆။ လုပ်ဆောင်ချက်ဆိုင်ရာ ကွတ်ကီးများ",
  "လုပ်ဆောင်ချက်ဆိုင်ရာ ကွတ်ကီးများသည် သင့်ရွေးချယ်မှုများကို မှတ်ထားပြီး အတွေ့အကြုံကို တိုးတက်စေသည်။ ဤကွတ်ကီးများသည် အခြားဝဘ်ဆိုက်များတွင် သင့်လှုပ်ရှားမှုကို ခြေရာမခံပါ၊ ဥပဒေခွင့်ပြုသည့်နေရာတွင်သာ အသုံးပြုပါသည်။",
  "၇။ ခွဲခြမ်းစိတ်ဖြာမှု ကွတ်ကီးများ",
  "Corner Bagel သည် လက်ရှိတွင် ခွဲခြမ်းစိတ်ဖြာမှု ကွတ်ကီးများ မသုံးပါ။ နောင်တွင် ခွဲခြမ်းစိတ်ဖြာမှု ကိရိယာများ ထည့်သွင်းပါက လာရောက်သူများကို အသိပေးပြီး၊ ဖွင့်မီ သဘောတူညီရန် အခွင့်အရေး ပေးပါမည်။",
  "၈။ ကြော်ငြာနှင့် စျေးကွက်ရှာဖွေရေး ကွတ်ကီးများ",
  "Corner Bagel သည် လက်ရှိတွင် ကြော်ငြာ သို့မဟုတ် ပြန်လည်ပစ်မှတ်ထားသော ကွတ်ကီးများ မထည့်ပါ။ ကွတ်ကီးများဖြင့် စုဆောင်းရရှိသော ကိုယ်ရေးအချက်အလက်များကို ကြော်ငြာရည်ရွယ်ချက်ဖြင့် မရောင်းချပါ။",
  "၉။ တတိယအဖွဲ့အစည်း ကွတ်ကီးများ",
  "ကျွန်ုပ်တို့၏ ဝဘ်ဆိုက်သည် အွန်လိုင်း အော်ဒါအတွက် Toast အပါအဝင် တတိယအဖွဲ့အစည်း ဝန်ဆောင်မှုများကို အသုံးပြုနိုင်ပါသည်။ ဤဝန်ဆောင်မှုပေးသူများသည် ၎င်းတို့၏ ကိုယ်ပိုင် ကိုယ်ရေးအချက်အလက်နှင့် ကွတ်ကီးမူဝါဒများအရ ကိုယ်ပိုင်ကွတ်ကီးများ ထည့်နိုင်ပါသည်။",
  "၁၀။ Toast ဖြင့် အော်ဒါမှာယူခြင်း",
  "Toast မှ ပံ့ပိုးသော အွန်လိုင်း အော်ဒါပလက်ဖောင်းကို အသုံးပြုသည့်အခါ Toast သည် အော်ဒါလုပ်ငန်း လည်ပတ်ရန် လိုအပ်သော ကွတ်ကီးများ ထည့်နိုင်ပါသည်။ Toast ၏ ကိုယ်ရေးအချက်အလက်နှင့် ကွတ်ကီးဆိုင်ရာ လုပ်ထုံးလုပ်နည်းများသည် Toast ၏ ကိုယ်ပိုင်မူဝါဒများအရ ဖြစ်ပါသည်။ အော်ဒါမတင်မီ ထိုမူဝါဒများကို ဖတ်ရှုရန် Corner Bagel မှ တိုက်တွန်းပါသည်။",
  "၁၁။ ကွတ်ကီး ရွေးချယ်မှုများ စီမံခြင်း",
  "ကျွန်ုပ်တို့၏ ကွတ်ကီးအကြောင်းကြားချက်မှ မလိုအပ်သော ကွတ်ကီးများကို လက်ခံခြင်း၊ ငြင်းပယ်ခြင်း သို့မဟုတ် စိတ်ကြိုက်ပြင်ဆင်ခြင်း ပြုနိုင်ပါသည်။ ရွေးချယ်မှုများကို အချိန်မရွေး ပြောင်းလဲနိုင်ပါသည်။",
  "၁၂။ ဘရောက်ဇာ ထိန်းချုပ်မှုများ",
  "ဘရောက်ဇာအများစုသည် ကွတ်ကီးများကို ပိတ်ရန် သို့မဟုတ် ဖျက်ရန် ခွင့်ပြုပါသည်။ မဖြစ်မနေလိုအပ်သော ကွတ်ကီးများကို ပိတ်ပါက အွန်လိုင်းအော်ဒါ အပါအဝင် ဝဘ်ဆိုက်၏ အချို့အပိုင်းများ မှန်ကန်စွာ အလုပ်မလုပ်နိုင်ပါ။",
  "၁၃။ သဘောတူညီချက်နှင့် ရုပ်သိမ်းခြင်း",
  "ဥပဒေက လိုအပ်သည့်အခါ မလိုအပ်သော ကွတ်ကီးများ မထည့်မီ သဘောတူညီချက် ရယူပါသည်။ သဘောတူညီချက်ကို ကွတ်ကီးရွေးချယ်မှုစင်တာ သို့မဟုတ် ဘရောက်ဇာဆက်တင်များမှ အချိန်မရွေး ရုပ်သိမ်းနိုင်ပါသည်။",
  "၁၄။ အချက်အလက် မျှဝေခြင်း",
  "ကျွန်ုပ်တို့သည် ဝဘ်ဆိုက်လည်ပတ်ရန် သို့မဟုတ် အွန်လိုင်းအော်ဒါများ လုပ်ဆောင်ရန် ကူညီပေးသော ယုံကြည်စိတ်ချရသည့် ဝန်ဆောင်မှုပေးသူများ (Toast အပါအဝင်) နှင့်၊ သို့မဟုတ် ဥပဒေက လိုအပ်သည့်အခါ ကွတ်ကီးဆိုင်ရာ အချက်အလက်များကို မျှဝေနိုင်ပါသည်။ ကွတ်ကီးများဖြင့် စုဆောင်းရရှိသော ကိုယ်ရေးအချက်အလက်များကို မရောင်းချပါ။",
  "၁၅။ ပြောင်းလဲမှုများ",
  "ကျွန်ုပ်တို့သည် ဤကွတ်ကီးမူဝါဒကို အခါအားလျော်စွာ မွမ်းမံနိုင်ပါသည်။ အရေးပါသော ပြောင်းလဲမှုများကို နောက်ဆုံးမွမ်းမံသည့်ရက်စွဲ ပြင်ဆင်ခြင်းဖြင့် ဖော်ပြပါမည်။",
  "၁၆။ ဆက်သွယ်ရန် အချက်အလက်",
  "Corner Bagel၊ Public Entity Holdings မှ လုပ်ငန်းလည်ပတ်သည်။ အီးမေးလ်− {email}",
  "ဤကွတ်ကီးမူဝါဒ သို့မဟုတ် သင့်ကိုယ်ရေးအချက်အလက် အခွင့်အရေးများနှင့် ပတ်သက်၍ မေးခွန်းရှိပါက အထက်ပါ အီးမေးလ်သို့ ဆက်သွယ်ပါ။",
];

const myPrivacy = [
  "ကိုယ်ရေးအချက်အလက် မူဝါဒ",
  "အာဏာသက်ရောက်သည့်ရက်− ၂၀၂၆ ခုနှစ် ဇူလိုင်လ ၈ ရက်",
  "Corner Bagel (“Corner Bagel”၊ “ကျွန်ုပ်တို့”) တွင် သင့်ကိုယ်ရေးအချက်အလက်ကို လေးစားပါသည်။ ဤမူဝါဒသည် သင်သည် ကျွန်ုပ်တို့၏ ဝဘ်ဆိုက်သို့ ဝင်ရောက်ခြင်း၊ အော်ဒါတင်ခြင်း၊ စာရင်းသွင်းခြင်း၊ ပရိုမိုးရှင်းများတွင် ပါဝင်ခြင်း သို့မဟုတ် အခြားနည်းဖြင့် ကျွန်ုပ်တို့နှင့် ဆက်သွယ်သည့်အခါ အချက်အလက်များကို မည်သို့ စုဆောင်း၊ အသုံးပြု၊ ထုတ်ဖော်နှင့် ကာကွယ်သည်ကို ရှင်းပြပါသည်။",
  "ကျွန်ုပ်တို့၏ ဝဘ်ဆိုက် သို့မဟုတ် ဝန်ဆောင်မှုများကို အသုံးပြုခြင်းဖြင့် ဤကိုယ်ရေးအချက်အလက်မူဝါဒကို သဘောတူသည်ဟု မှတ်ယူပါသည်။",
  "ကျွန်ုပ်တို့ စုဆောင်းသော အချက်အလက်များ",
  "သင် ပေးအပ်သော အချက်အလက်များ",
  "အောက်ပါတို့ကို စုဆောင်းနိုင်ပါသည်−",
  "အမည်",
  "အီးမေးလ်လိပ်စာ",
  "ဖုန်းနံပါတ်",
  "ငွေတောင်းခံမှုနှင့် ငွေပေးချေမှု အချက်အလက်",
  "ပို့ဆောင်ခြင်း သို့မဟုတ် လာယူခြင်း အချက်အလက်",
  "အော်ဒါ မှတ်တမ်း",
  "အမှတ်စုဆောင်း သို့မဟုတ် ဆုလာဘ် အကောင့် အချက်အလက် (သက်ဆိုင်ပါက)",
  "အလိုအလျောက် စုဆောင်းရရှိသော အချက်အလက်များ",
  "ကျွန်ုပ်တို့၏ ဝဘ်ဆိုက်သို့ ဝင်ရောက်သည့်အခါ အောက်ပါတို့ကို စုဆောင်းနိုင်ပါသည်−",
  "IP လိပ်စာ",
  "ဘရောက်ဇာ အမျိုးအစား",
  "စက်ပစ္စည်း အချက်အလက်",
  "လည်ပတ်မှုစနစ်",
  "ကြည့်ရှုခဲ့သော စာမျက်နှာများ",
  "ဝဘ်ဆိုက်တွင် အသုံးပြုခဲ့သော အချိန်",
  "လမ်းညွှန်ပေးခဲ့သော ဝဘ်ဆိုက်များ",
  "ကွတ်ကီးများနှင့် အလားတူ နည်းပညာများ",
  "သင့်အချက်အလက်များကို မည်သို့ အသုံးပြုသနည်း",
  "အောက်ပါတို့အတွက် သင့်အချက်အလက်များကို အသုံးပြုပါသည်−",
  "အော်ဒါများ လက်ခံပြီး ဆောင်ရွက်ရန်",
  "သင့်အော်ဒါနှင့် ပတ်သက်၍ ဆက်သွယ်ရန်",
  "ဖောက်သည် အထောက်အပံ့ ပေးရန်",
  "ကျွန်ုပ်တို့၏ ကုန်ပစ္စည်းနှင့် ဝန်ဆောင်မှုများ တိုးတက်စေရန်",
  "သင့်အတွေ့အကြုံကို ကိုယ်ပိုင်ပုံစံ ဖြစ်စေရန်",
  "သတင်းလွှာ၊ ပရိုမိုးရှင်းနှင့် အထူးကမ်းလှမ်းချက်များ ပေးပို့ရန် (သင် သဘောတူပါက)",
  "အမှတ်စုဆောင်း သို့မဟုတ် ဆုလာဘ် အစီအစဉ်များ လည်ပတ်ရန်",
  "လိမ်လည်မှု ကာကွယ်ပြီး လုံခြုံရေး ထိန်းသိမ်းရန်",
  "ဥပဒေဆိုင်ရာ တာဝန်များ လိုက်နာရန်",
  "စျေးကွက်ရှာဖွေရေး ဆက်သွယ်မှုများ",
  "ကျွန်ုပ်တို့၏ စာရင်းတွင် ပါဝင်ပါက အောက်ပါတို့နှင့် ပတ်သက်သော သတင်းများ ပေးပို့နိုင်ပါသည်−",
  "မီနူး အသစ်များ",
  "ရာသီအလိုက် ကမ်းလှမ်းချက်များ",
  "ပရိုမိုးရှင်းများ",
  "အခမ်းအနားများ",
  "ဆိုင်၏ ကြေညာချက်များ",
  "ကျွန်ုပ်တို့၏ အီးမေးလ်များတွင် ပါဝင်သော စာရင်းမှထွက်ရန် လင့်ခ်ကို နှိပ်၍ အချိန်မရွေး ရပ်တန့်နိုင်ပါသည်။",
  "ကွတ်ကီးများနှင့် ခြေရာခံခြင်း",
  "ကျွန်ုပ်တို့၏ ဝဘ်ဆိုက်သည် အောက်ပါတို့အတွက် ကွတ်ကီးများနှင့် အလားတူနည်းပညာများ အသုံးပြုနိုင်ပါသည်−",
  "အသုံးပြုသူ၏ ရွေးချယ်မှုများ မှတ်ထားရန်",
  "ဝဘ်ဆိုက် လုပ်ဆောင်ချက် တိုးတက်စေရန်",
  "ဝဘ်ဆိုက် အသွားအလာ ခွဲခြမ်းစိတ်ဖြာရန်",
  "စျေးကွက်ရှာဖွေရေး ထိရောက်မှု တိုင်းတာရန်",
  "ဘရောက်ဇာအများစုသည် ဆက်တင်များမှ ကွတ်ကီးများ ပိတ်ခွင့်ပြုသော်လည်း၊ ထိုသို့ပြုလုပ်ပါက ဝဘ်ဆိုက်၏ အချို့လုပ်ဆောင်ချက်များ ထိခိုက်နိုင်ပါသည်။",
  "ငွေပေးချေမှု အချက်အလက်",
  "ငွေပေးချေမှုများကို ယုံကြည်စိတ်ချရသော ပြင်ပ ငွေပေးချေမှု ဝန်ဆောင်မှုပေးသူများမှတစ်ဆင့် ဆောင်ရွက်ပါသည်။",
  "Corner Bagel သည် ငွေပေးချေမှုကတ်၏ နံပါတ်အပြည့်အစုံကို ကျွန်ုပ်တို့၏ ဆာဗာများတွင် မသိမ်းဆည်းပါ။",
  "အချက်အလက် မျှဝေခြင်း",
  "ကျွန်ုပ်တို့သည် သင့်ကိုယ်ရေးအချက်အလက်များကို မရောင်းချပါ။",
  "ကျွန်ုပ်တို့၏ လုပ်ငန်းလည်ပတ်ရန် ကူညီပေးသော ယုံကြည်စိတ်ချရသည့် ဝန်ဆောင်မှုပေးသူများနှင့် အချက်အလက်များ မျှဝေနိုင်ပါသည်။ ၎င်းတို့တွင် အောက်ပါတို့ ပါဝင်သည်−",
  "ငွေပေးချေမှု ဆောင်ရွက်ပေးသူများ",
  "အွန်လိုင်း အော်ဒါ ဝန်ဆောင်မှုပေးသူများ",
  "ပို့ဆောင်ရေး မိတ်ဖက်များ",
  "အီးမေးလ် စျေးကွက်ရှာဖွေရေး ပလက်ဖောင်းများ",
  "ဝဘ်ဆိုက် ဟိုစ်တင် ဝန်ဆောင်မှုပေးသူများ",
  "ခွဲခြမ်းစိတ်ဖြာမှု ဝန်ဆောင်မှုပေးသူများ",
  "ဤဝန်ဆောင်မှုပေးသူများသည် ကျွန်ုပ်တို့ကိုယ်စား ဝန်ဆောင်မှုပေးရန်အတွက်သာ သင့်အချက်အလက်များကို အသုံးပြုခွင့်ရှိပါသည်။ ဥပဒေက လိုအပ်ပါက သို့မဟုတ် ကျွန်ုပ်တို့၏ ဥပဒေဆိုင်ရာ အခွင့်အရေးများ ကာကွယ်ရန်လည်း အချက်အလက်များ ထုတ်ဖော်နိုင်ပါသည်။",
  "အချက်အလက် လုံခြုံရေး",
  "သင့်အချက်အလက်များ ကာကွယ်ရန်အတွက် စီးပွားရေးအရ သင့်လျော်သော စီမံခန့်ခွဲမှု၊ နည်းပညာနှင့် ရုပ်ပိုင်းဆိုင်ရာ ကာကွယ်မှုများ ဆောင်ရွက်ပါသည်။",
  "သင့်အချက်အလက်များ ကာကွယ်ရန် ကြိုးစားနေသော်လည်း၊ အီလက်ထရွန်နစ် ပို့ဆောင်မှု သို့မဟုတ် သိမ်းဆည်းမှု နည်းလမ်းတိုင်းသည် လုံးဝ လုံခြုံသည်ဟု မဆိုနိုင်ပါ။",
  "အချက်အလက် သိမ်းဆည်းမှု",
  "အောက်ပါတို့အတွက် လိုအပ်သည့် ကာလအတွင်းသာ ကိုယ်ရေးအချက်အလက်များကို သိမ်းဆည်းပါသည်−",
  "အော်ဒါများ ဆောင်ရွက်ရန်",
  "တောင်းဆိုထားသော ဝန်ဆောင်မှုများ ပေးအပ်ရန်",
  "ဥပဒေနှင့် စာရင်းကိုင်ဆိုင်ရာ လိုအပ်ချက်များ ပြည့်မီရန်",
  "အငြင်းပွားမှုများ ဖြေရှင်းရန်",
  "ကျွန်ုပ်တို့၏ သဘောတူညီချက်များ အတည်ပြုရန်",
  "သင့် ကိုယ်ရေးအချက်အလက် အခွင့်အရေးများ",
  "သင်နေထိုင်ရာ ပြည်နယ် သို့မဟုတ် နိုင်ငံပေါ်မူတည်၍ သင့်ကိုယ်ရေးအချက်အလက်နှင့် ပတ်သက်သော အောက်ပါ အခွင့်အရေးများ ရှိနိုင်ပါသည်−",
  "သင့်အချက်အလက်များကို ကြည့်ရှုခွင့်",
  "မမှန်ကန်သော အချက်အလက်များ ပြင်ဆင်ခွင့်",
  "ကိုယ်ရေးအချက်အလက် ဖျက်ရန် တောင်းဆိုခွင့်",
  "သင့်အချက်အလက် မိတ္တူ တောင်းဆိုခွင့်",
  "အချို့ စျေးကွက်ရှာဖွေရေး ဆက်သွယ်မှုများမှ ထွက်ခွင့်",
  "ဤအခွင့်အရေးများ ကျင့်သုံးရန် {email} သို့ ဆက်သွယ်ပါ။",
  "အလုပ်လျှောက်ထားသူများ",
  "ကျွန်ုပ်တို့ထံ အလုပ်လျှောက်ပါက လျှောက်လွှာတွင် သင်ဖြည့်သွင်းသည့် အချက်အလက်များကို စုဆောင်းပါသည်— အမည်နှင့် ဆက်သွယ်ရန်အချက်အလက်၊ နေထိုင်သည့်မြို့၊ သင်ရွေးချယ်သည့် ရာထူးနှင့် အလုပ်လုပ်နိုင်သည့်အချိန်၊ သင်ကိုယ်တိုင် ထည့်လိုသည့် ပညာရေး၊ အလုပ်အတွေ့အကြုံနှင့် ထောက်ခံသူများ၊ ထို့အပြင် သင်ရေးသားထားသည့် အဖြေများ။ ၎င်းတို့ကို အင်တာဗျူးခေါ်မည်၊ မခေါ်မည် ဆုံးဖြတ်ရန်အတွက်သာ အသုံးပြုပြီး အခြားမည်သည့်အတွက်မျှ မသုံးပါ။",
  "လျှောက်ထားသူများအား လူမျိုး၊ ဘာသာ၊ အသက်၊ မသန်စွမ်းမှု၊ နိုင်ငံသား၊ ကျား/မ၊ လိင်စိတ်တိမ်းညွတ်မှု၊ အိမ်ထောင်ရေးအခြေအနေ သို့မဟုတ် စစ်မှုထမ်းခဲ့မှုတို့ကို မမေးသလို ထည့်သွင်းစဉ်းစားခြင်းလည်း မပြုပါ။ ဤလျှောက်လွှာဖြင့် နောက်ခံစစ်ဆေးမှု မပြုလုပ်ပါ။ နောင်တွင် နောက်ခံစစ်ဆေးမှုသည် ခန့်အပ်ရေးလုပ်ငန်းစဉ်၏ အစိတ်အပိုင်းဖြစ်လာပါက ဖက်ဒရယ်ဥပဒေအရ သီးခြားစာဖြင့် ခွင့်ပြုချက် တောင်းခံပါမည်။",
  "လျှောက်လွှာများကို စာရွက်စာတမ်းအဖြစ် ကျွန်ုပ်တို့၏ ခန့်အပ်ရေးအီးမေးလ်သို့ ပို့ပေးပါသည်။ မည်သည့် ဖောက်သည်ဒေတာဘေ့စ်တွင်မျှ ထည့်သွင်းခြင်းမရှိသလို ကြော်ငြာအတွက်လည်း မသုံးပါ။ တစ်နှစ်အထိ သိမ်းဆည်းပြီးနောက် ဖျက်ပစ်ပါသည်။ လျှောက်ထားသူများသည် အထက်ဖော်ပြပါ အခွင့်အရေးများ — ကြည့်ရှုခွင့်၊ ပြင်ဆင်ခွင့်၊ ဖျက်ခွင့်နှင့် မိတ္တူရယူခွင့် — အတူတူ ရရှိပြီး {email} သို့ စာရေးကာ ကျင့်သုံးနိုင်ပါသည်။",
  "ဖောင်ဖြည့်နေစဥ်တွင် မပြီးစီးသေး မူကြမ်းကို သင့်ဘရောင်ဇာထဲမှာ သိမ်းထားပြီး ပြန်လာဆက်ဖြည့်နိုင်ပါတယ်။ ကျွန်ုပ်တို့ဆီ မပို့ပါ။ တင်သွင်းချိန် သို့မဟုတ် ဆက်မဖြည့်ဘဲ ဆယ့်ငါးမိနစ်ကြာလျှင် ဖျက်ပစ်ပြီး၊ “အစကနေ ပြန်စရန်” နှိပ်လျှင် ချကျင်း ပျောက်သွားပါတယ်။ အင်္ဂလိပ်မဟုတ်သော ဘာသာဖြင့် ရေးပါက ဖတ်နိုင်ရန် ဘာသာပြန်ပြီး၊ သင်ရေးထားသည့် မူရင်းကိုလည်း ဘာသာပြန်နှင့်အတူ သိမ်းထားပါတယ်။",
  "ကလေးများ၏ ကိုယ်ရေးအချက်အလက်",
  "ကျွန်ုပ်တို့၏ ဝန်ဆောင်မှုများသည် အသက် ၁၃ နှစ်အောက် ကလေးများအတွက် မရည်ရွယ်ပါ၊ ကလေးများထံမှ ကိုယ်ရေးအချက်အလက်များကို သိလျက်နှင့် မစုဆောင်းပါ။ သင့်လျော်သော သဘောတူညီချက်မရှိဘဲ ကလေးတစ်ဦး၏ အချက်အလက်များ စုဆောင်းမိကြောင်း သိရှိပါက ချက်ချင်း ဖျက်ပစ်ပါမည်။",
  "တတိယအဖွဲ့အစည်း လင့်ခ်များ",
  "ကျွန်ုပ်တို့၏ ဝဘ်ဆိုက်တွင် တတိယအဖွဲ့အစည်း ဝဘ်ဆိုက်များ သို့မဟုတ် ဝန်ဆောင်မှုများသို့ လင့်ခ်များ ပါဝင်နိုင်ပါသည်။ ထိုတတိယအဖွဲ့အစည်းများ၏ ကိုယ်ရေးအချက်အလက် လုပ်ထုံးလုပ်နည်းများ သို့မဟုတ် အကြောင်းအရာများအတွက် ကျွန်ုပ်တို့ တာဝန်မယူပါ။",
  "မွမ်းမံမှုများ",
  "ကျွန်ုပ်တို့သည် ဤကိုယ်ရေးအချက်အလက်မူဝါဒကို အခါအားလျော်စွာ မွမ်းမံနိုင်ပါသည်။ ပြောင်းလဲမှုရှိပါက အထက်ပါ အာဏာသက်ရောက်သည့်ရက်စွဲကို ပြင်ဆင်ပါမည်။ မွမ်းမံပြီးနောက် ဝန်ဆောင်မှုများ ဆက်လက်အသုံးပြုခြင်းသည် ပြင်ဆင်ထားသော မူဝါဒကို လက်ခံသည်ဟု မှတ်ယူပါသည်။",
  "ဆက်သွယ်ရန်",
  "Corner Bagel။ အီးမေးလ်− {email}",
];


// ——— French ———

const frCookie = [
  "Politique relative aux cookies",
  "Exploité par Public Entity Holdings",
  "Dernière mise à jour : 1 août 2026",
  "1. Introduction",
  "Cette politique relative aux cookies explique comment Corner Bagel (« Corner Bagel », « nous », « notre » ou « nos »), exploité par Public Entity Holdings, utilise les cookies et les technologies de suivi similaires sur notre site web. Elle doit être lue conjointement avec notre {privacyPolicy}.",
  "Cette politique s'adresse aux visiteurs qui utilisent notre site web aux États-Unis, y compris en Californie. Lorsque la loi applicable l'exige, notamment le California Consumer Privacy Act (CCPA) tel que modifié par le California Privacy Rights Act (CPRA), nous recueillons votre consentement avant de déposer des cookies non essentiels.",
  "2. Qu'est-ce qu'un cookie ?",
  "Les cookies sont de petits fichiers texte enregistrés sur votre appareil lorsque vous visitez notre site web. Ils aident à reconnaître votre appareil, à mémoriser vos préférences, à améliorer les fonctionnalités et à prendre en charge la commande en ligne. Les cookies peuvent être de session ou persistants, et de première ou de tierce partie.",
  "3. Comment nous utilisons les cookies",
  "Nous utilisons des cookies pour garantir le bon fonctionnement et la sécurité de notre site web ; mémoriser vos préférences ; personnaliser votre expérience ; analyser les performances du site (si cette fonction est activée à l'avenir) ; et prendre en charge les services de commande en ligne, y compris ceux fournis par Toast. Nous n'utilisons pas de cookies pour collecter des informations personnelles sensibles au-delà de ce qui est nécessaire à l'exécution des services que vous demandez.",
  "4. Catégories de cookies que nous utilisons",
  "Strictement nécessaires",
  "Indispensables à la sécurité, à la gestion des sessions, à la prévention de la fraude, au paiement et au fonctionnement du site. Aucun consentement requis.",
  "Fonctionnels",
  "Mémorisent les réglages d'accessibilité et les préférences de commande. Consentement requis le cas échéant.",
  "Analytiques",
  "Actuellement inactifs. S'ils sont introduits, ils nous aideront à comprendre l'utilisation du site et ne seront activés qu'après obtention du consentement.",
  "Publicité et marketing",
  "Corner Bagel n'utilise actuellement aucun cookie publicitaire ou marketing.",
  "5. Cookies strictement nécessaires",
  "Ces cookies sont indispensables pour naviguer sur le site, consulter les menus, envoyer les formulaires de contact et finaliser les commandes en ligne. Sans eux, les services demandés ne peuvent pas être fournis.",
  "6. Cookies fonctionnels",
  "Les cookies fonctionnels mémorisent vos préférences et améliorent votre expérience. Ils ne suivent pas votre activité sur d'autres sites et ne sont utilisés que dans les limites autorisées par la loi.",
  "7. Cookies analytiques",
  "Corner Bagel n'utilise actuellement aucun cookie analytique. Si des outils d'analyse sont ajoutés à l'avenir, les visiteurs en seront informés et pourront donner leur consentement avant toute activation.",
  "8. Cookies publicitaires et marketing",
  "Corner Bagel ne dépose actuellement aucun cookie publicitaire ou de reciblage. Nous ne vendons pas les informations personnelles collectées au moyen de cookies à des fins publicitaires.",
  "9. Cookies tiers",
  "Notre site web peut faire appel à des services tiers, dont Toast pour la commande en ligne. Ces prestataires peuvent déposer leurs propres cookies, régis par leurs propres politiques de confidentialité et de cookies.",
  "10. Commande via Toast",
  "Lorsque vous utilisez la plateforme de commande en ligne fournie par Toast, Toast peut déposer les cookies nécessaires au fonctionnement de l'expérience de commande. Les pratiques de Toast en matière de confidentialité et de cookies sont régies par ses propres politiques. Corner Bagel invite ses clients à en prendre connaissance avant de passer commande.",
  "11. Gestion des préférences de cookies",
  "Vous pouvez accepter, refuser ou personnaliser les cookies non essentiels au moyen de notre bandeau de cookies. Vos préférences peuvent être modifiées à tout moment.",
  "12. Réglages du navigateur",
  "La plupart des navigateurs permettent de bloquer ou de supprimer les cookies. Bloquer les cookies strictement nécessaires peut empêcher certaines parties du site, dont la commande en ligne, de fonctionner correctement.",
  "13. Consentement et retrait",
  "Lorsque la loi l'exige, nous recueillons votre consentement avant de déposer des cookies non essentiels. Ce consentement peut être retiré à tout moment depuis le centre de préférences ou les réglages de votre navigateur.",
  "14. Partage des données",
  "Nous pouvons partager des informations liées aux cookies avec des prestataires de confiance qui nous aident à exploiter notre site web ou à traiter les commandes en ligne, dont Toast, ou lorsque la loi l'exige. Nous ne vendons pas les informations personnelles collectées au moyen de cookies.",
  "15. Modifications",
  "Nous pouvons mettre à jour cette politique relative aux cookies de temps à autre. Les modifications importantes seront signalées par la mise à jour de la date de dernière mise à jour.",
  "16. Nous contacter",
  "Corner Bagel, exploité par Public Entity Holdings. E-mail : {email}",
  "Pour toute question concernant cette politique relative aux cookies ou vos droits en matière de confidentialité, écrivez-nous à l'adresse ci-dessus.",
];

const frPrivacy = [
  "Politique de confidentialité",
  "Date d'entrée en vigueur : 8 juillet 2026",
  "Chez Corner Bagel (« Corner Bagel », « nous », « notre » ou « nos »), nous respectons votre vie privée. Cette politique explique comment nous collectons, utilisons, divulguons et protégeons vos informations lorsque vous visitez notre site web, passez une commande, rejoignez notre liste de diffusion, participez à des promotions ou interagissez autrement avec notre entreprise.",
  "En utilisant notre site web ou nos services, vous acceptez cette politique de confidentialité.",
  "Informations que nous collectons",
  "Informations que vous fournissez",
  "Nous pouvons collecter :",
  "Nom",
  "Adresse e-mail",
  "Numéro de téléphone",
  "Informations de facturation et de paiement",
  "Informations de livraison ou de retrait",
  "Historique des commandes",
  "Informations de compte fidélité ou de récompenses (le cas échéant)",
  "Informations collectées automatiquement",
  "Lorsque vous visitez notre site web, nous pouvons collecter :",
  "Adresse IP",
  "Type de navigateur",
  "Informations sur l'appareil",
  "Système d'exploitation",
  "Pages consultées",
  "Temps passé sur notre site web",
  "Sites référents",
  "Cookies et technologies similaires",
  "Comment nous utilisons vos informations",
  "Nous utilisons vos informations pour :",
  "Traiter et exécuter les commandes",
  "Communiquer au sujet de vos commandes",
  "Fournir une assistance client",
  "Améliorer nos produits et services",
  "Personnaliser votre expérience",
  "Envoyer des lettres d'information, des promotions et des offres spéciales (si vous y consentez)",
  "Faire fonctionner les programmes de fidélité ou de récompenses",
  "Prévenir la fraude et assurer la sécurité",
  "Respecter les obligations légales",
  "Communications marketing",
  "Si vous vous inscrivez à notre liste de diffusion, nous pouvons vous envoyer des nouvelles concernant :",
  "Les nouveautés du menu",
  "Les offres de saison",
  "Les promotions",
  "Les événements",
  "Les annonces de la boutique",
  "Vous pouvez vous désabonner à tout moment en cliquant sur le lien de désabonnement présent dans nos e-mails.",
  "Cookies et suivi",
  "Notre site web peut utiliser des cookies et des technologies similaires pour :",
  "Mémoriser les préférences des utilisateurs",
  "Améliorer le fonctionnement du site",
  "Analyser le trafic du site",
  "Mesurer l'efficacité des actions marketing",
  "La plupart des navigateurs permettent de désactiver les cookies dans leurs réglages, même si cela peut affecter certaines fonctionnalités du site.",
  "Informations de paiement",
  "Les paiements sont traités par des prestataires de paiement tiers de confiance.",
  "Corner Bagel ne conserve pas les numéros complets de cartes bancaires sur ses serveurs.",
  "Partage des informations",
  "Nous ne vendons pas vos informations personnelles.",
  "Nous pouvons partager des informations avec des prestataires de confiance qui nous aident à faire fonctionner notre activité, dont :",
  "Les prestataires de paiement",
  "Les fournisseurs de commande en ligne",
  "Les partenaires de livraison",
  "Les plateformes d'e-mailing",
  "Les hébergeurs du site web",
  "Les fournisseurs d'outils d'analyse",
  "Ces prestataires ne sont autorisés à utiliser vos informations que pour exécuter des services pour notre compte. Nous pouvons également divulguer des informations si la loi l'exige ou pour protéger nos droits.",
  "Sécurité des données",
  "Nous mettons en œuvre des mesures administratives, techniques et physiques commercialement raisonnables destinées à protéger vos informations.",
  "Malgré tous nos efforts, aucun mode de transmission ou de stockage électronique n'est totalement sûr.",
  "Conservation des données",
  "Nous ne conservons vos informations personnelles que le temps nécessaire pour :",
  "Exécuter les commandes",
  "Fournir les services demandés",
  "Respecter les obligations légales et comptables",
  "Régler les litiges",
  "Faire respecter nos accords",
  "Vos droits en matière de confidentialité",
  "Selon votre État ou votre pays de résidence, vous pouvez disposer de droits sur vos informations personnelles, notamment celui de :",
  "Accéder à vos informations",
  "Corriger des informations inexactes",
  "Demander la suppression de vos informations personnelles",
  "Demander une copie de vos informations",
  "Refuser certaines communications marketing",
  "Pour exercer ces droits, écrivez-nous à {email}.",
  "Candidats à un emploi",
  "Si vous postulez chez nous, nous recueillons ce que vous saisissez dans le formulaire de candidature : vos nom et coordonnées, la ville où vous habitez, les postes et les disponibilités que vous sélectionnez, les études, l'expérience professionnelle et les références que vous choisissez d'ajouter, ainsi que vos réponses rédigées. Nous nous en servons pour décider de vous rencontrer, et pour rien d'autre.",
  "Nous ne demandons pas aux candidats leur origine, leur religion, leur âge, leur handicap, leur nationalité, leur genre, leur orientation sexuelle, leur situation familiale ou leur statut d'ancien combattant, et nous n'en tenons pas compte. Nous ne réalisons aucune vérification d'antécédents via ce formulaire. Si une telle vérification devait un jour faire partie du recrutement, nous demanderions votre autorisation séparément et par écrit, comme la loi fédérale l'exige.",
  "Les candidatures nous parviennent sous forme de document à notre adresse de recrutement. Elles ne sont ajoutées à aucune base de données clients et ne servent pas au marketing. Nous les conservons un an au maximum, puis nous les supprimons. Les candidats disposent des mêmes droits que ceux décrits ci-dessus — accès, rectification, suppression et copie — et peuvent les exercer en écrivant à {email}.",
  "Pendant que vous remplissez le formulaire, un brouillon inachevé est conservé dans votre propre navigateur pour que vous puissiez y revenir. Il ne nous est pas envoyé, il est supprimé à l'envoi ou si vous le laissez quinze minutes, et « Recommencer » l'efface immédiatement. Si vous rédigez vos réponses dans une autre langue que l'anglais, nous les traduisons pour pouvoir les lire, et nous conservons vos mots d'origine à côté de la traduction.",
  "Vie privée des enfants",
  "Nos services ne s'adressent pas aux enfants de moins de 13 ans, et nous ne collectons pas sciemment d'informations personnelles auprès d'enfants. Si nous apprenons que des informations concernant un enfant ont été collectées sans le consentement approprié, nous les supprimerons rapidement.",
  "Liens vers des sites tiers",
  "Notre site web peut contenir des liens vers des sites ou des services tiers. Nous ne sommes pas responsables des pratiques de confidentialité ni du contenu de ces tiers.",
  "Mises à jour",
  "Nous pouvons mettre à jour cette politique de confidentialité de temps à autre. En cas de modification, nous réviserons la date d'entrée en vigueur ci-dessus. Continuer à utiliser nos services après une mise à jour vaut acceptation de la politique révisée.",
  "Contact",
  "Corner Bagel. E-mail : {email}",
];

// ——— Italian ———

const itCookie = [
  "Informativa sui cookie",
  "Gestito da Public Entity Holdings",
  "Ultimo aggiornamento: 1 agosto 2026",
  "1. Introduzione",
  "Questa informativa sui cookie spiega come Corner Bagel (« Corner Bagel », « noi », « nostro » o « ci »), gestito da Public Entity Holdings, utilizza i cookie e tecnologie di tracciamento simili sul nostro sito web. Va letta insieme alla nostra {privacyPolicy}.",
  "Questa informativa è rivolta ai visitatori che usano il nostro sito web negli Stati Uniti, California compresa. Dove la legge applicabile lo richiede, incluso il California Consumer Privacy Act (CCPA) come modificato dal California Privacy Rights Act (CPRA), raccogliamo il consenso prima di installare cookie non essenziali.",
  "2. Che cosa sono i cookie?",
  "I cookie sono piccoli file di testo salvati sul tuo dispositivo quando visiti il nostro sito web. Aiutano a riconoscere il dispositivo, ricordare le preferenze, migliorare le funzionalità e supportare gli ordini online. I cookie possono essere di sessione o persistenti, di prima o di terza parte.",
  "3. Come usiamo i cookie",
  "Usiamo i cookie per garantire che il sito funzioni correttamente e in sicurezza; ricordare le tue preferenze; personalizzare la tua esperienza; analizzare le prestazioni del sito (se attivate in futuro); e supportare i servizi di ordinazione online, compresi quelli forniti da Toast. Non usiamo i cookie per raccogliere informazioni personali sensibili oltre a quanto necessario per completare i servizi che richiedi.",
  "4. Categorie di cookie che usiamo",
  "Strettamente necessari",
  "Essenziali per la sicurezza, la gestione della sessione, la prevenzione delle frodi, il pagamento e il funzionamento del sito. Non richiedono consenso.",
  "Funzionali",
  "Ricordano le impostazioni di accessibilità e le preferenze di ordinazione. Richiedono il consenso dove previsto.",
  "Analitici",
  "Attualmente non attivi. Se verranno introdotti, ci aiuteranno a capire come viene usato il sito e saranno attivati solo dopo aver ottenuto il consenso.",
  "Pubblicità e marketing",
  "Corner Bagel al momento non usa cookie pubblicitari o di marketing.",
  "5. Cookie strettamente necessari",
  "Questi cookie servono per navigare nel sito, consultare i menu, inviare i moduli di contatto e completare gli ordini online. Senza di essi i servizi richiesti non possono essere forniti.",
  "6. Cookie funzionali",
  "I cookie funzionali ricordano le tue preferenze e migliorano la tua esperienza. Non tracciano l'attività su altri siti e sono usati solo dove la legge lo consente.",
  "7. Cookie analitici",
  "Corner Bagel al momento non usa cookie analitici. Se in futuro verranno aggiunti strumenti di analisi, i visitatori saranno informati e potranno dare il consenso prima dell'attivazione.",
  "8. Cookie pubblicitari e di marketing",
  "Corner Bagel al momento non installa cookie pubblicitari o di retargeting. Non vendiamo per fini pubblicitari le informazioni personali raccolte tramite cookie.",
  "9. Cookie di terze parti",
  "Il nostro sito web può usare servizi di terze parti, tra cui Toast per gli ordini online. Questi fornitori possono installare i propri cookie, soggetti alle loro informative su privacy e cookie.",
  "10. Ordini con Toast",
  "Quando usi la piattaforma di ordinazione online fornita da Toast, Toast può installare i cookie necessari a far funzionare l'esperienza di ordinazione. Le pratiche di Toast in materia di privacy e cookie sono regolate dalle sue informative. Corner Bagel invita i clienti a leggerle prima di ordinare.",
  "11. Gestione delle preferenze sui cookie",
  "Puoi accettare, rifiutare o personalizzare i cookie non essenziali tramite il nostro banner. Le preferenze possono essere modificate in qualsiasi momento.",
  "12. Impostazioni del browser",
  "La maggior parte dei browser consente di bloccare o eliminare i cookie. Bloccare i cookie strettamente necessari può impedire il corretto funzionamento di parti del sito, ordini online compresi.",
  "13. Consenso e revoca",
  "Dove la legge lo richiede, raccogliamo il consenso prima di installare cookie non essenziali. Il consenso può essere revocato in qualsiasi momento dal centro preferenze o dalle impostazioni del browser.",
  "14. Condivisione dei dati",
  "Possiamo condividere informazioni relative ai cookie con fornitori di fiducia che ci aiutano a gestire il sito o a elaborare gli ordini online, tra cui Toast, oppure quando la legge lo richiede. Non vendiamo le informazioni personali raccolte tramite cookie.",
  "15. Modifiche",
  "Possiamo aggiornare questa informativa sui cookie di tanto in tanto. Le modifiche sostanziali saranno segnalate aggiornando la data di ultimo aggiornamento.",
  "16. Contatti",
  "Corner Bagel, gestito da Public Entity Holdings. E-mail: {email}",
  "Per domande su questa informativa sui cookie o sui tuoi diritti in materia di privacy, scrivici all'indirizzo qui sopra.",
];

const itPrivacy = [
  "Informativa sulla privacy",
  "Data di entrata in vigore: 8 luglio 2026",
  "Da Corner Bagel (« Corner Bagel », « noi », « nostro » o « ci ») rispettiamo la tua privacy. Questa informativa spiega come raccogliamo, usiamo, comunichiamo e proteggiamo le informazioni quando visiti il nostro sito web, fai un ordine, ti iscrivi alla nostra lista, partecipi a promozioni o interagisci in altro modo con la nostra attività.",
  "Usando il nostro sito web o i nostri servizi, accetti questa informativa sulla privacy.",
  "Informazioni che raccogliamo",
  "Informazioni che ci fornisci",
  "Possiamo raccogliere:",
  "Nome",
  "Indirizzo e-mail",
  "Numero di telefono",
  "Dati di fatturazione e pagamento",
  "Informazioni di consegna o ritiro",
  "Storico degli ordini",
  "Dati dell'account fedeltà o premi (se applicabile)",
  "Informazioni raccolte automaticamente",
  "Quando visiti il nostro sito web, possiamo raccogliere:",
  "Indirizzo IP",
  "Tipo di browser",
  "Informazioni sul dispositivo",
  "Sistema operativo",
  "Pagine visitate",
  "Tempo trascorso sul nostro sito web",
  "Siti di provenienza",
  "Cookie e tecnologie simili",
  "Come usiamo le tue informazioni",
  "Usiamo le tue informazioni per:",
  "Elaborare ed evadere gli ordini",
  "Comunicare riguardo ai tuoi ordini",
  "Fornire assistenza clienti",
  "Migliorare i nostri prodotti e servizi",
  "Personalizzare la tua esperienza",
  "Inviare newsletter, promozioni e offerte speciali (se hai dato il consenso)",
  "Gestire i programmi fedeltà o premi",
  "Prevenire le frodi e mantenere la sicurezza",
  "Adempiere agli obblighi di legge",
  "Comunicazioni di marketing",
  "Se ti iscrivi alla nostra lista, possiamo mandarti aggiornamenti su:",
  "Nuove voci del menu",
  "Proposte di stagione",
  "Promozioni",
  "Eventi",
  "Annunci del negozio",
  "Puoi disiscriverti in qualsiasi momento cliccando il link di disiscrizione presente nelle nostre e-mail.",
  "Cookie e tracciamento",
  "Il nostro sito web può usare cookie e tecnologie simili per:",
  "Ricordare le preferenze dell'utente",
  "Migliorare il funzionamento del sito",
  "Analizzare il traffico del sito",
  "Misurare l'efficacia del marketing",
  "La maggior parte dei browser consente di disattivare i cookie dalle impostazioni, anche se farlo può influire su alcune funzioni del sito.",
  "Dati di pagamento",
  "I pagamenti sono elaborati da fornitori di pagamento terzi di fiducia.",
  "Corner Bagel non conserva sui propri server i numeri completi delle carte di pagamento.",
  "Condivisione delle informazioni",
  "Non vendiamo le tue informazioni personali.",
  "Possiamo condividere informazioni con fornitori di fiducia che ci aiutano a gestire la nostra attività, tra cui:",
  "Elaboratori di pagamento",
  "Fornitori di ordinazione online",
  "Partner di consegna",
  "Piattaforme di e-mail marketing",
  "Fornitori di hosting del sito",
  "Fornitori di strumenti di analisi",
  "Questi fornitori possono usare le tue informazioni solo per svolgere servizi per nostro conto. Possiamo inoltre comunicare informazioni se richiesto dalla legge o per tutelare i nostri diritti.",
  "Sicurezza dei dati",
  "Adottiamo misure amministrative, tecniche e fisiche commercialmente ragionevoli, pensate per proteggere le tue informazioni.",
  "Pur impegnandoci a proteggere le tue informazioni, nessun metodo di trasmissione o archiviazione elettronica è completamente sicuro.",
  "Conservazione dei dati",
  "Conserviamo le informazioni personali solo per il tempo necessario a:",
  "Evadere gli ordini",
  "Fornire i servizi richiesti",
  "Rispettare obblighi legali e contabili",
  "Risolvere controversie",
  "Far valere i nostri accordi",
  "I tuoi diritti sulla privacy",
  "A seconda dello stato o del paese in cui risiedi, potresti avere diritti sulle tue informazioni personali, tra cui:",
  "Accedere alle tue informazioni",
  "Correggere informazioni inesatte",
  "Chiedere la cancellazione delle informazioni personali",
  "Chiedere una copia delle tue informazioni",
  "Rinunciare a determinate comunicazioni di marketing",
  "Per esercitare questi diritti, scrivici a {email}.",
  "Candidati a un impiego",
  "Se ti candidi per lavorare da noi, raccogliamo quello che inserisci nel modulo di candidatura: nome e recapiti, la città in cui vivi, le mansioni e le disponibilità che selezioni, gli studi, le esperienze di lavoro e le referenze che scegli di aggiungere, e le tue risposte scritte. Li usiamo per decidere se incontrarti, e per nient'altro.",
  "Non chiediamo ai candidati di etnia, religione, età, disabilità, nazionalità, genere, orientamento sessuale, stato civile o servizio militare, e non ne teniamo conto. Con questo modulo non facciamo controlli sui precedenti. Se un giorno un controllo dovesse diventare parte della selezione, chiederemmo la tua autorizzazione a parte e per iscritto, come richiede la legge federale.",
  "Le candidature arrivano come documento all'indirizzo email delle assunzioni. Non finiscono in nessun database clienti e non vengono usate per il marketing. Le conserviamo al massimo un anno, poi le cancelliamo. I candidati hanno gli stessi diritti descritti sopra — accesso, rettifica, cancellazione e copia — e possono esercitarli scrivendo a {email}.",
  "Mentre compili il modulo, una bozza incompleta resta nel tuo browser così puoi riprenderla. A noi non arriva, viene cancellata quando invii o se la lasci per quindici minuti, e «Ricomincia» la elimina subito. Se scrivi le risposte in una lingua diversa dall'inglese le traduciamo per poterle leggere, e teniamo accanto alla traduzione quello che hai scritto davvero.",
  "Privacy dei minori",
  "I nostri servizi non sono rivolti a minori di 13 anni e non raccogliamo consapevolmente informazioni personali dai bambini. Se veniamo a sapere che sono state raccolte informazioni di un minore senza il consenso adeguato, le cancelleremo tempestivamente.",
  "Link a terze parti",
  "Il nostro sito web può contenere link a siti o servizi di terze parti. Non siamo responsabili delle pratiche sulla privacy né dei contenuti di quelle terze parti.",
  "Aggiornamenti",
  "Possiamo aggiornare questa informativa sulla privacy di tanto in tanto. In caso di modifiche, rivedremo la data di entrata in vigore qui sopra. Continuare a usare i nostri servizi dopo un aggiornamento costituisce accettazione dell'informativa rivista.",
  "Contatti",
  "Corner Bagel. E-mail: {email}",
];

// ——— Persian ———

const faCookie = [
  "سیاست کوکی",
  "اداره‌شده توسط Public Entity Holdings",
  "آخرین به‌روزرسانی: ۱ اوت ۲۰۲۶",
  "۱. مقدمه",
  "این سیاست کوکی توضیح می‌دهد که Corner Bagel («Corner Bagel»، «ما» یا «مال ما»)، که توسط Public Entity Holdings اداره می‌شود، چگونه از کوکی‌ها و فناوری‌های ردیابی مشابه در وب‌سایت خود استفاده می‌کند. این سیاست باید همراه با {privacyPolicy} ما خوانده شود.",
  "این سیاست برای بازدیدکنندگانی است که از وب‌سایت ما در ایالات متحده، از جمله کالیفرنیا، استفاده می‌کنند. جایی که قانون قابل اجرا ایجاب کند، از جمله قانون حریم خصوصی مصرف‌کنندهٔ کالیفرنیا (CCPA) با اصلاحات قانون حقوق حریم خصوصی کالیفرنیا (CPRA)، پیش از قرار دادن کوکی‌های غیرضروری رضایت می‌گیریم.",
  "۲. کوکی چیست؟",
  "کوکی‌ها فایل‌های متنی کوچکی هستند که هنگام بازدید از وب‌سایت ما روی دستگاه شما ذخیره می‌شوند. آن‌ها به شناسایی دستگاه شما، به یاد سپردن ترجیحات، بهبود کارکردها و پشتیبانی از سفارش آنلاین کمک می‌کنند. کوکی‌ها ممکن است موقت یا ماندگار، و متعلق به خود سایت یا به شخص ثالث باشند.",
  "۳. چگونه از کوکی‌ها استفاده می‌کنیم",
  "از کوکی‌ها استفاده می‌کنیم تا وب‌سایت ما درست و امن کار کند؛ ترجیحات شما به یاد بماند؛ تجربهٔ شما شخصی شود؛ عملکرد وب‌سایت تحلیل شود (اگر در آینده فعال شود)؛ و از خدمات سفارش آنلاین، از جمله آن‌هایی که با Toast کار می‌کنند، پشتیبانی شود. از کوکی‌ها برای جمع‌آوری اطلاعات شخصی حساس، فراتر از آنچه برای انجام خدمات درخواستی شما لازم است، استفاده نمی‌کنیم.",
  "۴. دسته‌های کوکی که استفاده می‌کنیم",
  "کاملاً ضروری",
  "برای امنیت، مدیریت نشست، پیشگیری از تقلب، پرداخت و کارکرد وب‌سایت لازم‌اند. رضایت نمی‌خواهند.",
  "کارکردی",
  "تنظیمات دسترس‌پذیری و ترجیحات سفارش را به یاد می‌سپارند. در جای لازم رضایت می‌خواهند.",
  "تحلیلی",
  "در حال حاضر فعال نیستند. اگر افزوده شوند، به ما کمک می‌کنند استفاده از وب‌سایت را بفهمیم و تنها پس از گرفتن رضایت فعال خواهند شد.",
  "تبلیغات و بازاریابی",
  "Corner Bagel در حال حاضر از کوکی‌های تبلیغاتی یا بازاریابی استفاده نمی‌کند.",
  "۵. کوکی‌های کاملاً ضروری",
  "این کوکی‌ها برای گشتن در وب‌سایت، دیدن منوها، ارسال فرم‌های تماس و تکمیل سفارش‌های آنلاین لازم‌اند. بدون آن‌ها نمی‌توان خدمات درخواستی را ارائه کرد.",
  "۶. کوکی‌های کارکردی",
  "کوکی‌های کارکردی ترجیحات شما را به یاد می‌سپارند و تجربه‌تان را بهتر می‌کنند. این کوکی‌ها فعالیت شما را در سایت‌های دیگر دنبال نمی‌کنند و تنها در حدی که قانون اجازه می‌دهد به کار می‌روند.",
  "۷. کوکی‌های تحلیلی",
  "Corner Bagel در حال حاضر از کوکی‌های تحلیلی استفاده نمی‌کند. اگر در آینده ابزارهای تحلیلی افزوده شوند، به بازدیدکنندگان اطلاع داده می‌شود و پیش از فعال‌سازی فرصت رضایت دادن خواهند داشت.",
  "۸. کوکی‌های تبلیغاتی و بازاریابی",
  "Corner Bagel در حال حاضر کوکی تبلیغاتی یا هدف‌گیری مجدد قرار نمی‌دهد. اطلاعات شخصی گردآوری‌شده از راه کوکی‌ها را برای مقاصد تبلیغاتی نمی‌فروشیم.",
  "۹. کوکی‌های شخص ثالث",
  "وب‌سایت ما ممکن است از خدمات شخص ثالث، از جمله Toast برای سفارش آنلاین، استفاده کند. این ارائه‌دهندگان ممکن است کوکی‌های خود را قرار دهند که تابع سیاست‌های حریم خصوصی و کوکی خودشان است.",
  "۱۰. سفارش با Toast",
  "وقتی از سکوی سفارش آنلاین Toast استفاده می‌کنید، Toast ممکن است کوکی‌های لازم برای کارکرد تجربهٔ سفارش را قرار دهد. رویه‌های حریم خصوصی و کوکی Toast تابع سیاست‌های خود Toast است. Corner Bagel از مشتریان می‌خواهد پیش از سفارش آن سیاست‌ها را بخوانند.",
  "۱۱. مدیریت ترجیحات کوکی",
  "می‌توانید کوکی‌های غیرضروری را با نوار کوکی ما بپذیرید، رد کنید یا سفارشی کنید. ترجیحات را هر زمان می‌توان تغییر داد.",
  "۱۲. کنترل‌های مرورگر",
  "بیشتر مرورگرها امکان مسدود کردن یا حذف کوکی‌ها را می‌دهند. مسدود کردن کوکی‌های کاملاً ضروری ممکن است مانع کارکرد درست بخش‌هایی از وب‌سایت، از جمله سفارش آنلاین، شود.",
  "۱۳. رضایت و پس گرفتن آن",
  "جایی که قانون ایجاب کند، پیش از قرار دادن کوکی‌های غیرضروری رضایت می‌گیریم. رضایت را هر زمان می‌توان از مرکز ترجیحات کوکی یا تنظیمات مرورگر پس گرفت.",
  "۱۴. اشتراک‌گذاری داده‌ها",
  "ممکن است اطلاعات مربوط به کوکی‌ها را با ارائه‌دهندگان خدمات مورد اعتمادی که به اداره وب‌سایت یا پردازش سفارش‌های آنلاین کمک می‌کنند، از جمله Toast، یا هنگامی که قانون ایجاب کند، به اشتراک بگذاریم. اطلاعات شخصی گردآوری‌شده از راه کوکی‌ها را نمی‌فروشیم.",
  "۱۵. تغییرات",
  "ممکن است این سیاست کوکی را هر از گاهی به‌روز کنیم. تغییرات مهم با به‌روزرسانی تاریخ آخرین به‌روزرسانی نشان داده می‌شود.",
  "۱۶. اطلاعات تماس",
  "Corner Bagel، اداره‌شده توسط Public Entity Holdings. ایمیل: {email}",
  "اگر دربارهٔ این سیاست کوکی یا حقوق حریم خصوصی خود پرسشی دارید، با نشانی ایمیل بالا با ما تماس بگیرید.",
];

const faPrivacy = [
  "سیاست حریم خصوصی",
  "تاریخ اجرا: ۸ ژوئیهٔ ۲۰۲۶",
  "در Corner Bagel («Corner Bagel»، «ما» یا «مال ما») به حریم خصوصی شما احترام می‌گذاریم. این سیاست توضیح می‌دهد که وقتی از وب‌سایت ما بازدید می‌کنید، سفارش می‌دهید، به فهرست ایمیلی ما می‌پیوندید، در تخفیف‌ها شرکت می‌کنید یا به هر شکل دیگری با کسب‌وکار ما در ارتباط‌اید، چگونه اطلاعات را گردآوری، استفاده، افشا و محافظت می‌کنیم.",
  "با استفاده از وب‌سایت یا خدمات ما، این سیاست حریم خصوصی را می‌پذیرید.",
  "اطلاعاتی که گردآوری می‌کنیم",
  "اطلاعاتی که شما می‌دهید",
  "ممکن است این‌ها را گردآوری کنیم:",
  "نام",
  "نشانی ایمیل",
  "شمارهٔ تلفن",
  "اطلاعات صورت‌حساب و پرداخت",
  "اطلاعات ارسال یا تحویل حضوری",
  "تاریخچهٔ سفارش‌ها",
  "اطلاعات حساب وفاداری یا پاداش (در صورت وجود)",
  "اطلاعاتی که خودکار گردآوری می‌شود",
  "وقتی از وب‌سایت ما بازدید می‌کنید، ممکن است این‌ها را گردآوری کنیم:",
  "نشانی IP",
  "نوع مرورگر",
  "اطلاعات دستگاه",
  "سیستم‌عامل",
  "صفحه‌های بازدیدشده",
  "زمان سپری‌شده در وب‌سایت ما",
  "وب‌سایت‌های ارجاع‌دهنده",
  "کوکی‌ها و فناوری‌های مشابه",
  "چگونه از اطلاعات شما استفاده می‌کنیم",
  "از اطلاعات شما برای این کارها استفاده می‌کنیم:",
  "پردازش و انجام سفارش‌ها",
  "ارتباط دربارهٔ سفارش‌های شما",
  "ارائهٔ پشتیبانی مشتری",
  "بهتر کردن محصولات و خدمات",
  "شخصی‌سازی تجربهٔ شما",
  "فرستادن خبرنامه، تخفیف و پیشنهادهای ویژه (وقتی خودتان بخواهید)",
  "اجرای برنامه‌های وفاداری یا پاداش",
  "پیشگیری از تقلب و حفظ امنیت",
  "رعایت الزامات قانونی",
  "پیام‌های بازاریابی",
  "اگر در فهرست ایمیلی ما عضو شوید، ممکن است دربارهٔ این‌ها به شما خبر دهیم:",
  "اقلام تازهٔ منو",
  "پیشنهادهای فصلی",
  "تخفیف‌ها",
  "رویدادها",
  "اطلاعیه‌های فروشگاه",
  "هر زمان می‌توانید با کلیک روی پیوند لغو عضویت در ایمیل‌های ما اشتراک را لغو کنید.",
  "کوکی‌ها و ردیابی",
  "وب‌سایت ما ممکن است از کوکی‌ها و فناوری‌های مشابه برای این کارها استفاده کند:",
  "به یاد سپردن ترجیحات کاربر",
  "بهتر کردن کارکرد وب‌سایت",
  "تحلیل ترافیک وب‌سایت",
  "سنجش اثربخشی بازاریابی",
  "بیشتر مرورگرها امکان غیرفعال کردن کوکی‌ها را از تنظیمات می‌دهند، هرچند این کار ممکن است روی برخی امکانات وب‌سایت اثر بگذارد.",
  "اطلاعات پرداخت",
  "پرداخت‌ها از طریق ارائه‌دهندگان پرداخت شخص ثالث مورد اعتماد پردازش می‌شوند.",
  "Corner Bagel شمارهٔ کامل کارت‌های پرداخت را روی سرورهای خود ذخیره نمی‌کند.",
  "اشتراک‌گذاری اطلاعات",
  "ما اطلاعات شخصی شما را نمی‌فروشیم.",
  "ممکن است اطلاعات را با ارائه‌دهندگان خدمات مورد اعتمادی که به اداره کسب‌وکار ما کمک می‌کنند به اشتراک بگذاریم، از جمله:",
  "پردازشگران پرداخت",
  "ارائه‌دهندگان سفارش آنلاین",
  "همکاران ارسال",
  "سکوهای بازاریابی ایمیلی",
  "ارائه‌دهندگان میزبانی وب‌سایت",
  "ارائه‌دهندگان ابزارهای تحلیلی",
  "این ارائه‌دهندگان تنها اجازه دارند از اطلاعات شما برای انجام خدمات از طرف ما استفاده کنند. همچنین ممکن است اطلاعات را در صورت الزام قانونی یا برای حفاظت از حقوق قانونی خود افشا کنیم.",
  "امنیت داده‌ها",
  "تدابیر اداری، فنی و فیزیکی متعارفی را به کار می‌گیریم که برای محافظت از اطلاعات شما طراحی شده‌اند.",
  "با آنکه برای محافظت از اطلاعات شما می‌کوشیم، هیچ روش انتقال یا ذخیره‌سازی الکترونیکی کاملاً ایمن نیست.",
  "نگهداری داده‌ها",
  "اطلاعات شخصی را تنها تا زمانی نگه می‌داریم که برای این کارها لازم است:",
  "انجام سفارش‌ها",
  "ارائهٔ خدمات درخواستی",
  "برآوردن الزامات قانونی و حسابداری",
  "حل اختلاف‌ها",
  "اجرای توافق‌های ما",
  "حقوق حریم خصوصی شما",
  "بسته به ایالت یا کشور محل اقامتتان، ممکن است دربارهٔ اطلاعات شخصی خود حقوقی داشته باشید، از جمله:",
  "دسترسی به اطلاعاتتان",
  "اصلاح اطلاعات نادرست",
  "درخواست حذف اطلاعات شخصی",
  "درخواست رونوشتی از اطلاعاتتان",
  "انصراف از برخی پیام‌های بازاریابی",
  "برای اعمال این حقوق، با {email} تماس بگیرید.",
  "متقاضیان کار",
  "اگر برای کار نزد ما درخواست بدهید، آنچه را در فرم درخواست وارد می‌کنید گردآوری می‌کنیم: نام و اطلاعات تماس، شهری که در آن زندگی می‌کنید، سِمت‌ها و ساعت‌هایی که انتخاب می‌کنید، تحصیلات، سابقهٔ کار و معرف‌هایی که خودتان می‌افزایید، و پاسخ‌های نوشتاری‌تان. از این‌ها فقط برای تصمیم‌گیری دربارهٔ مصاحبه استفاده می‌کنیم و برای هیچ کار دیگری.",
  "از متقاضیان دربارهٔ نژاد، مذهب، سن، معلولیت، ملیت، جنسیت، گرایش جنسی، وضعیت تأهل یا سابقهٔ نظامی نمی‌پرسیم و آن‌ها را در نظر نمی‌گیریم. با این فرم بررسی سوابق انجام نمی‌دهیم. اگر روزی بررسی سوابق بخشی از فرایند استخدام شود، طبق قانون فدرال اجازهٔ آن را جداگانه و کتبی خواهیم خواست.",
  "درخواست‌ها به‌صورت یک سند به ایمیل استخدام ما می‌رسند. به هیچ پایگاه دادهٔ مشتریان افزوده نمی‌شوند و برای بازاریابی به کار نمی‌روند. حداکثر یک سال نگه می‌داریم و سپس حذف می‌کنیم. متقاضیان همان حقوق بالا را دارند — دسترسی، اصلاح، حذف و دریافت رونوشت — و می‌توانند با نوشتن به {email} آن‌ها را اعمال کنند.",
  "تا وقتی فرم را پر می‌کنید، پیش‌نویسی ناتمام در مرورگر خودتان نگه داشته می‌شود تا بتوانید برگردید. برای ما فرستاده نمی‌شود، هنگام ارسال یا اگر پانزده دقیقه رهایش کنید حذف می‌شود، و «از نو شروع کنید» فوری پاکش می‌کند. اگر پاسخ‌ها را به زبانی جز انگلیسی بنویسید، آن‌ها را ترجمه می‌کنیم تا بتوانیم بخوانیم، و عین نوشتهٔ خودتان را همراه ترجمه نگه می‌داریم.",
  "حریم خصوصی کودکان",
  "خدمات ما متوجه کودکان زیر ۱۳ سال نیست و ما آگاهانه اطلاعات شخصی از کودکان گردآوری نمی‌کنیم. اگر آگاه شویم که اطلاعات کودکی بدون رضایت مناسب گردآوری شده است، آن را بی‌درنگ حذف می‌کنیم.",
  "پیوندهای شخص ثالث",
  "وب‌سایت ما ممکن است پیوندهایی به وب‌سایت‌ها یا خدمات شخص ثالث داشته باشد. ما مسئول رویه‌های حریم خصوصی یا محتوای آن اشخاص ثالث نیستیم.",
  "به‌روزرسانی‌ها",
  "ممکن است این سیاست حریم خصوصی را هر از گاهی به‌روز کنیم. هنگام تغییر، تاریخ اجرای بالا را بازبینی می‌کنیم. ادامهٔ استفاده از خدمات ما پس از به‌روزرسانی به معنای پذیرش سیاست بازبینی‌شده است.",
  "تماس",
  "Corner Bagel. ایمیل: {email}",
];

export const POLICY_PACKS: PolicyPacks = {
  fr: {
    cookie: rebuild(EN_POLICIES.cookie, frCookie),
    privacy: rebuild(EN_POLICIES.privacy, frPrivacy),
    goBack: "Retour",
    governedBy:
      "Ceci est une traduction de courtoisie. La version anglaise fait foi ; en cas de divergence, le texte anglais prévaut.",
  },
  it: {
    cookie: rebuild(EN_POLICIES.cookie, itCookie),
    privacy: rebuild(EN_POLICIES.privacy, itPrivacy),
    goBack: "Indietro",
    governedBy:
      "Questa è una traduzione di cortesia. Fa fede la versione inglese; in caso di differenze prevale il testo inglese.",
  },
  fa: {
    cookie: rebuild(EN_POLICIES.cookie, faCookie),
    privacy: rebuild(EN_POLICIES.privacy, faPrivacy),
    goBack: "بازگشت",
    governedBy:
      "این ترجمه‌ای برای راحتی شماست. نسخهٔ انگلیسی معتبر است؛ در صورت اختلاف، متن انگلیسی حاکم است.",
  },
  es: {
    cookie: rebuild(EN_POLICIES.cookie, esCookie),
    privacy: rebuild(EN_POLICIES.privacy, esPrivacy),
    goBack: "Volver",
    governedBy:
      "Esta es una traducción de cortesía. La versión en inglés es la que rige; si hay alguna diferencia, prevalece el texto en inglés.",
  },
  ko: {
    cookie: rebuild(EN_POLICIES.cookie, koCookie),
    privacy: rebuild(EN_POLICIES.privacy, koPrivacy),
    goBack: "돌아가기",
    governedBy:
      "이 문서는 이해를 돕기 위한 번역본입니다. 효력을 갖는 것은 영문본이며, 내용이 다를 경우 영문본이 우선합니다.",
  },
  ur: {
    cookie: rebuild(EN_POLICIES.cookie, urCookie),
    privacy: rebuild(EN_POLICIES.privacy, urPrivacy),
    goBack: "واپس جائیں",
    governedBy:
      "یہ سہولت کے لیے کیا گیا ترجمہ ہے۔ قانونی حیثیت انگریزی متن کی ہے؛ اختلاف کی صورت میں انگریزی متن معتبر ہو گا۔",
  },
  ja: {
    cookie: rebuild(EN_POLICIES.cookie, jaCookie),
    privacy: rebuild(EN_POLICIES.privacy, jaPrivacy),
    goBack: "戻る",
    governedBy:
      "これは参考のための翻訳です。効力を持つのは英語版であり、内容に相違がある場合は英語版が優先します。",
  },
  zh: {
    cookie: rebuild(EN_POLICIES.cookie, zhCookie),
    privacy: rebuild(EN_POLICIES.privacy, zhPrivacy),
    goBack: "返回",
    governedBy:
      "本文为方便阅读提供的译文。具有法律效力的是英文版；如有出入，以英文版为准。",
  },
  my: {
    cookie: rebuild(EN_POLICIES.cookie, myCookie),
    privacy: rebuild(EN_POLICIES.privacy, myPrivacy),
    goBack: "ပြန်သွားရန်",
    governedBy:
      "ဤစာသားသည် နားလည်ရလွယ်ကူစေရန် ဘာသာပြန်ထားခြင်း ဖြစ်ပါသည်။ တရားဝင်အာဏာတည်သည်မှာ အင်္ဂလိပ်ဘာသာ မူရင်းဖြစ်ပြီး၊ ကွဲလွဲမှုရှိပါက အင်္ဂလိပ်မူရင်းကို အတည်ယူပါသည်။",
  },
};
